SET mapred.job.queue.name=custscience;
SET hive.cli.print.header=true;
SET hive.variable.substitute.depth=100;

SET CAMPAIGN_VERSION = 1677806; SET CURRENT_BRAND = ON; SET CURRENT_COUNTRY = US;

--DROP DATABASE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION} CASCADE;
--CREATE DATABASE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION} 
--LOCATION '/consumers/custscience/xtghosh/${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.db';


USE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION};
SHOW TABLES;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1 
STORED AS ORC 
AS SELECT DISTINCT
CAMPAIGN_VERSION, 
CUSTOMER_KEY, 
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(EVENT_DATE,' ')[0],'MM/dd/yyyy'))) AS EVENT_DATE
FROM 
DB_CUSTBASE_PRODREFRESH.ODS_MAILINGEMAIL_T
WHERE CAMPAIGN_VERSION=${hiveconf:CAMPAIGN_VERSION};

SELECT COUNT(*) FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_2 STORED AS ORC AS
SELECT DISTINCT
T1.CUSTOMER_KEY,
(
CASE WHEN T4.CUSTOMER_KEY > 0 THEN 1 ELSE 0 END
) AS EMAILOPENFLAG
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1 T1
INNER JOIN
(
SELECT DISTINCT 
T2.CUSTOMER_KEY, 
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(EVENT_DATE,'MM/dd/yyyy'))) AS EVENT_DATE 
FROM 
DB_CUSTBASE_PRODREFRESH.ODS_EMAILOPENS_T T2
WHERE 
T2.CAMPAIGN_VERSION = ${hiveconf:CAMPAIGN_VERSION}
) T4
ON 
T1.CUSTOMER_KEY = T4.CUSTOMER_KEY
INNER JOIN
(
SELECT 
MIN(TO_DATE(EVENT_DATE)) AS START_DT, 
DATE_ADD(MIN(TO_DATE(EVENT_DATE)), 1) AS END_DT 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1
) T3
WHERE
UNIX_TIMESTAMP(TO_DATE(T4.EVENT_DATE), 'yyyy-MM-dd') BETWEEN
UNIX_TIMESTAMP(T3.START_DT, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T3.END_DT, 'yyyy-MM-dd')
;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_3;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_3 STORED AS ORC AS
SELECT DISTINCT
T1.CUSTOMER_KEY,
(
CASE WHEN T4.CUSTOMER_KEY > 0 THEN 1 ELSE 0 END
) AS EMAILCLICKFLAG
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1 T1
INNER JOIN
(
SELECT 
T2.CUSTOMER_KEY, 
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CLICK_DATE,'MM/dd/yyyy'))) AS CLICK_DATE 
FROM 
DB_CUSTBASE_PRODREFRESH.ODS_EMAILCLICKS_T T2
WHERE 
T2.CAMPAIGN_VERSION = ${hiveconf:CAMPAIGN_VERSION}
) T4
ON 
T1.CUSTOMER_KEY = T4.CUSTOMER_KEY
INNER JOIN
(
SELECT 
MIN(TO_DATE(EVENT_DATE)) AS START_DT, 
DATE_ADD(MIN(TO_DATE(EVENT_DATE)), 1) AS END_DT 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1
) T3
WHERE
UNIX_TIMESTAMP(TO_DATE(T4.CLICK_DATE), 'yyyy-MM-dd') BETWEEN
UNIX_TIMESTAMP(T3.START_DT, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T3.END_DT, 'yyyy-MM-dd')
;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED STORED AS ORC AS
SELECT
T1.*, T2.EMAILOPENFLAG, T3.EMAILCLICKFLAG
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1 T1
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_2 T2
ON
T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_3 T3
ON
T1.CUSTOMER_KEY = T3.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_1;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_2;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED_3;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_1;	   
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_1 STORED AS ORC AS
SELECT
T1.*
FROM 
(
SELECT
CUSTOMER_KEY,
ORDER_STATUS, 
TRANSACTION_TYPE_CD,
TRANSACTION_NUM,
ORDER_NUM,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SHIP_DATE,'dd-MMM-yy'))) AS SHIP_DATE,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(DEMAND_DATE,'dd-MMM-yy'))) AS DEMAND_DATE,
BRAND,
COUNTRY,
(
CASE
WHEN ORDER_STATUS = 'R' THEN 
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SHIP_DATE,'dd-MMM-yy')))
ELSE TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(DEMAND_DATE,'dd-MMM-yy')))
END
) AS ORDER_DATE
FROM 
DB_CUSTBASE_PRODREFRESH.CUST_ORD_TXN_XREF_T
WHERE
BRAND='${hiveconf:CURRENT_BRAND}' AND COUNTRY='${hiveconf:CURRENT_COUNTRY}' AND TRANSACTION_TYPE_CD IN ('S', 'M', 'R')
) T1
INNER JOIN
(
SELECT DISTINCT CUSTOMER_KEY
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED 
) T2
ON T1.CUSTOMER_KEY=T2.CUSTOMER_KEY
INNER JOIN
(
SELECT 
MIN(TO_DATE(EVENT_DATE)) AS START_DT, 
DATE_ADD(MIN(TO_DATE(EVENT_DATE)), 1) AS END_DT 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED
) T3
WHERE 
(
(T1.ORDER_STATUS='R' AND
 UNIX_TIMESTAMP(T1.SHIP_DATE,'yyyy-MM-dd') BETWEEN
 UNIX_TIMESTAMP(T3.START_DT, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T3.END_DT, 'yyyy-MM-dd')
 ) OR
(T1.ORDER_STATUS='O' AND
 UNIX_TIMESTAMP(T1.DEMAND_DATE,'yyyy-MM-dd') BETWEEN
 UNIX_TIMESTAMP(T3.START_DT,   'yyyy-MM-dd') AND UNIX_TIMESTAMP(T3.END_DT, 'yyyy-MM-dd')
)
)
;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_2;	   
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_2 STORED AS ORC AS
SELECT
T1.*,
T2.LINE_NUM,
T2.ITEM_QTY,
T2.SALES_AMT,
T3.DISCOUNT_AMT,
T2.TOT_PRD_CST_AMT,
T2.PRODUCT_KEY
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_1 T1
INNER JOIN
MDS_NEW.ODS_ORDERLINE_T T2
ON
T1.TRANSACTION_NUM = T2.TRANSACTION_NUM
LEFT OUTER JOIN
(
SELECT 
TRANSACTION_NUM, LINE_NUM, SUM(DISCOUNT_AMT) AS DISCOUNT_AMT
FROM
MDS_NEW.ODS_ORDERLINE_DISCOUNTS_T
GROUP BY TRANSACTION_NUM, LINE_NUM
) T3
ON
T2.TRANSACTION_NUM = T3.TRANSACTION_NUM AND
T2.LINE_NUM = T3.LINE_NUM;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_ONL;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_ONL 
STORED AS ORC AS SELECT
T1.*,
CASE WHEN T3.NUM_TXNS_ONL > 0 THEN 1 ELSE 0 END AS ONL_RESPONDER,
T3.NUM_TXNS_ONL,
T3.ITEM_QTY_ONL,
T3.GROSS_SALES_AMT_ONL,
T3.DISCOUNT_AMT_ONL,
T3.TOT_PRD_CST_AMT_ONL,
T3.NET_SALES_AMT_ONL,
T3.NET_MARGIN_ONL
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED T1
LEFT OUTER JOIN
(
SELECT
T2.CUSTOMER_KEY,
COUNT(DISTINCT ORDER_NUM) AS NUM_TXNS_ONL,
SUM(T2.ITEM_QTY) AS ITEM_QTY_ONL,
SUM(T2.SALES_AMT) AS GROSS_SALES_AMT_ONL,
SUM(T2.DISCOUNT_AMT) AS DISCOUNT_AMT_ONL,
SUM(T2.TOT_PRD_CST_AMT) AS TOT_PRD_CST_AMT_ONL,
NVL(SUM(T2.SALES_AMT), 0) + NVL(SUM(T2.DISCOUNT_AMT), 0) AS NET_SALES_AMT_ONL,
NVL(SUM(T2.SALES_AMT), 0) + NVL(SUM(T2.DISCOUNT_AMT), 0) - NVL(SUM(T2.TOT_PRD_CST_AMT), 0) AS NET_MARGIN_ONL
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_2 T2
WHERE
T2.ORDER_STATUS = 'O' AND T2.SALES_AMT > 0  AND T2.ITEM_QTY > 0
GROUP BY 
T2.CUSTOMER_KEY
) T3
ON
T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
;





DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_RTL;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_RTL 
STORED AS ORC AS SELECT
T1.*,
CASE WHEN T3.NUM_TXNS_RTL > 0 THEN 1 ELSE 0 END AS RTL_RESPONDER,
T3.NUM_TXNS_RTL,
T3.ITEM_QTY_RTL,
T3.GROSS_SALES_AMT_RTL,
T3.DISCOUNT_AMT_RTL,
T3.TOT_PRD_CST_AMT_RTL,
T3.NET_SALES_AMT_RTL,
T3.NET_MARGIN_RTL
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED T1
LEFT OUTER JOIN
(
SELECT
T2.CUSTOMER_KEY,
COUNT(DISTINCT TRANSACTION_NUM) AS NUM_TXNS_RTL,
SUM(T2.ITEM_QTY) AS ITEM_QTY_RTL,
SUM(T2.SALES_AMT) AS GROSS_SALES_AMT_RTL,
SUM(T2.DISCOUNT_AMT) AS DISCOUNT_AMT_RTL,
SUM(T2.TOT_PRD_CST_AMT) AS TOT_PRD_CST_AMT_RTL,
NVL(SUM(T2.SALES_AMT), 0) + NVL(SUM(T2.DISCOUNT_AMT), 0) AS NET_SALES_AMT_RTL,
NVL(SUM(T2.SALES_AMT), 0) + NVL(SUM(T2.DISCOUNT_AMT), 0) - NVL(SUM(T2.TOT_PRD_CST_AMT), 0) AS NET_MARGIN_RTL
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_2 T2
WHERE
T2.ORDER_STATUS = 'R' AND T2.SALES_AMT > 0  AND T2.ITEM_QTY > 0
GROUP BY 
T2.CUSTOMER_KEY
) T3
ON
T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
;





DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM
STORED AS ORC AS SELECT
T1.CAMPAIGN_VERSION,
T1.CUSTOMER_KEY,
T1.EVENT_DATE,
T1.EMAILOPENFLAG,
T1.EMAILCLICKFLAG,
T1.RTL_RESPONDER,
T1.NUM_TXNS_RTL,
T1.ITEM_QTY_RTL,
T1.GROSS_SALES_AMT_RTL,
T1.DISCOUNT_AMT_RTL,
T1.TOT_PRD_CST_AMT_RTL,
T1.NET_SALES_AMT_RTL,
T1.NET_MARGIN_RTL,
T2.ONL_RESPONDER,
T2.NUM_TXNS_ONL,
T2.ITEM_QTY_ONL,
T2.GROSS_SALES_AMT_ONL,
T2.DISCOUNT_AMT_ONL,
T2.TOT_PRD_CST_AMT_ONL,
T2.NET_SALES_AMT_ONL,
T2.NET_MARGIN_ONL,
NVL(T1.RTL_RESPONDER,0) + NVL(T2.ONL_RESPONDER,0) AS RESPONDER,
NVL(T1.NUM_TXNS_RTL,0) + NVL(T2.NUM_TXNS_ONL,0) AS NUM_TXNS,
NVL(T1.ITEM_QTY_RTL,0) + NVL(T2.ITEM_QTY_ONL,0) AS ITEM_QTY,
NVL(T1.GROSS_SALES_AMT_RTL,0) + NVL(T2.GROSS_SALES_AMT_ONL,0) AS GROSS_SALES_AMT,
NVL(T1.DISCOUNT_AMT_RTL,0) + NVL(T2.DISCOUNT_AMT_ONL,0) AS DISCOUNT_AMT,
NVL(T1.TOT_PRD_CST_AMT_RTL,0) + NVL(T2.TOT_PRD_CST_AMT_ONL,0) AS TOT_PRD_CST_AMT,
NVL(T1.NET_SALES_AMT_RTL,0) + NVL(T2.NET_SALES_AMT_ONL,0) AS NET_SALES_AMT,
NVL(T1.NET_MARGIN_RTL,0) + NVL(T2.NET_MARGIN_ONL,0) AS NET_MARGIN
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_RTL T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_ONL T2
ON
T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
;


SELECT
COUNT(CUSTOMER_KEY) AS COUNT, 
SUM(RESPONDER) AS RESPONDERS,  SUM(RESPONDER)/COUNT(CUSTOMER_KEY) AS RESPONSE_RATE,
SUM(RTL_RESPONDER) AS RTL_RESPONDERS,  SUM(RTL_RESPONDER)/COUNT(CUSTOMER_KEY) AS RTL_RESPONSE_RATE,
SUM(ONL_RESPONDER) AS ONL_RESPONDERS,  SUM(ONL_RESPONDER)/COUNT(CUSTOMER_KEY) AS ONL_RESPONSE_RATE
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM;



DROP TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP;
DROP TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_1;
DROP TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_2;
DROP TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_ONL;
DROP TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_RESPONSE_GRP_RTL;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_1 AS 
SELECT 
T2.CUSTOMER_KEY,
(
CASE
WHEN T1.ORDER_STATUS = 'R' THEN T1.SHIP_DATE
ELSE TO_DATE(T1.DEMAND_DATE)
END
) AS ORDER_DATE,
T1.ORDER_STATUS, 
T1.TRANSACTION_TYPE_CD,
T1.TRANSACTION_NUM,
T1.ORDER_NUM,
T1.DEMAND_DATE,
T1.SHIP_DATE,
T1.BRAND,
T1.COUNTRY,
T1.PRIMARY_TENDER_TYPE
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T2 
LEFT OUTER JOIN
MDS_NEW.ODS_ORDERHEADER_T T1 
ON 
T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
INNER JOIN
(
SELECT 
MIN(TO_DATE(EVENT_DATE)) AS START_DT, 
DATE_ADD(MIN(TO_DATE(EVENT_DATE)), 1) AS END_DT 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED
) T3
WHERE
T1.COUNTRY='US' AND
(
(UNIX_TIMESTAMP(T1.SHIP_DATE,'yyyy-MM-dd') BETWEEN 
 UNIX_TIMESTAMP(DATE_SUB(T3.START_DT, 1 + 365), 'yyyy-MM-dd')  AND 
 UNIX_TIMESTAMP(DATE_SUB(T3.START_DT, 1), 'yyyy-MM-dd')  AND 
 T1.ORDER_STATUS = 'R'
) OR
(UNIX_TIMESTAMP(T1.DEMAND_DATE, 'yyyy-MM-dd_HH-mm-ss_Z') BETWEEN
 UNIX_TIMESTAMP(DATE_SUB(T3.START_DT, 1 + 365), 'yyyy-MM-dd')  AND 
 UNIX_TIMESTAMP(DATE_SUB(T3.START_DT, 1), 'yyyy-MM-dd')  AND 
 T1.ORDER_STATUS = 'O'
)
);



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_2
AS SELECT
T1.*,
T2.LINE_NUM,
T2.ITEM_QTY,
T2.SALES_AMT,
T3.DISCOUNT_AMT,
T2.TOT_PRD_CST_AMT,
(
CASE
WHEN T2.ON_SALE_FLAG='Y' THEN 1
ELSE NULL
END
) AS ONSALE_IND,
T2.PRODUCT_KEY
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_1 T1
INNER JOIN
MDS_NEW.ODS_ORDERLINE_T T2
ON
T1.TRANSACTION_NUM = T2.TRANSACTION_NUM
LEFT OUTER JOIN
(
SELECT 
TRANSACTION_NUM, LINE_NUM, SUM(DISCOUNT_AMT) AS DISCOUNT_AMT
FROM
MDS_NEW.ODS_ORDERLINE_DISCOUNTS_T
GROUP BY TRANSACTION_NUM, LINE_NUM
) T3
ON
T2.TRANSACTION_NUM = T3.TRANSACTION_NUM AND
T2.LINE_NUM = T3.LINE_NUM;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE 
AS SELECT
MAX(TO_DATE(ORDER_DATE)) AS MAXDATE, MIN(TO_DATE(ORDER_DATE)) AS MINDATE
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_2;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3 AS SELECT
T1.CUSTOMER_KEY, 
T1.TRANSACTION_NUM,
T1.ORDER_NUM,
T1.SHIP_DATE, 
T1.DEMAND_DATE, 
T1.BRAND, 
T1.COUNTRY, 
T1.ORDER_STATUS, 
T1.TRANSACTION_TYPE_CD, 
T1.PRIMARY_TENDER_TYPE, 
T1.ITEM_QTY, 
T1.SALES_AMT AS GROSS_SALES_AMT, 
T1.DISCOUNT_AMT, 
T1.TOT_PRD_CST_AMT, 
T1.ORDER_DATE,
T1.PRODUCT_KEY,
T1.ONSALE_IND,
T1.LINE_NUM,
(CASE
WHEN T1.ORDER_STATUS = 'O' THEN 1
ELSE NULL
END) AS FLAG_ONL,
(CASE
WHEN T1.ORDER_STATUS = 'R' THEN 1
ELSE NULL
END) AS FLAG_RTL,
(CASE
WHEN UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(DATE_SUB(T2.MAXDATE, 365), 'yyyy-MM-dd') AND 
T1.ORDER_STATUS = 'O' THEN ORDER_NUM
ELSE NULL
END) AS ORDER_NUM_12MO, 
(CASE
WHEN UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(DATE_SUB(T2.MAXDATE, 183), 'yyyy-MM-dd')  AND 
T1.ORDER_STATUS = 'O' THEN ORDER_NUM
ELSE NULL
END) AS ORDER_NUM_6MO, 
(CASE
WHEN UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(DATE_SUB(T2.MAXDATE, 365), 'yyyy-MM-dd')  AND 
T1.ORDER_STATUS = 'O' AND 
T1.PRIMARY_TENDER_TYPE IN ('BR','GP','ON','VB','VG','VO') THEN ORDER_NUM
ELSE NULL
END) AS ORDER_NUM_PLCC_12MO,
(CASE
WHEN UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(DATE_SUB(T2.MAXDATE, 183), 'yyyy-MM-dd')  AND 
T1.ORDER_STATUS = 'O' AND 
T1.PRIMARY_TENDER_TYPE IN ('BR','GP','ON','VB','VG','VO') THEN ORDER_NUM
ELSE NULL
END) AS ORDER_NUM_PLCC_6MO,
(CASE
WHEN UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(DATE_SUB(T2.MAXDATE, 365), 'yyyy-MM-dd')  THEN 1
ELSE NULL
END) AS FLAG_12MO,
(CASE
WHEN UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(DATE_SUB(T2.MAXDATE, 183), 'yyyy-MM-dd')  THEN 1
ELSE NULL
END) AS FLAG_6MO,
(CASE 
WHEN T1.PRIMARY_TENDER_TYPE IN ('BR','GP','ON','VB','VG','VO') THEN 1
ELSE NULL
END) AS PLCC_TXN,
(CASE 
WHEN T1.BRAND = 'GP' THEN 1
ELSE NULL
END) AS GP_FLAG,
(CASE 
WHEN T1.BRAND = 'BR' THEN 1
ELSE NULL
END) AS BR_FLAG,
(CASE 
WHEN T1.BRAND = 'ON' THEN 1
ELSE NULL
END) AS ON_FLAG,
(CASE 
WHEN T1.BRAND = 'AT' THEN 1
ELSE NULL
END) AS AT_FLAG,
(CASE 
WHEN T1.BRAND = 'BF' THEN 1
ELSE NULL
END) AS BF_FLAG,
(CASE 
WHEN T1.BRAND = 'GO' THEN 1
ELSE NULL
END) AS GO_FLAG
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_2 T1
INNER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2;	


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_1 
AS SELECT 
CUSTOMER_KEY,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) AS NET_SALES_AMT_6MO_SLS,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) AS NET_SALES_AMT_12MO_SLS,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_6MO_SLS,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_12MO_SLS,
SUM(DISCOUNT_AMT*FLAG_6MO) AS DISCOUNT_AMT_6MO_SLS, 
SUM(DISCOUNT_AMT*FLAG_12MO) AS DISCOUNT_AMT_12MO_SLS, 
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) - NVL(SUM(TOT_PRD_CST_AMT*FLAG_6MO),0)AS NET_MARGIN_6MO_SLS,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) - NVL(SUM(TOT_PRD_CST_AMT*FLAG_12MO),0)AS NET_MARGIN_12MO_SLS,
SUM(ITEM_QTY*FLAG_6MO) AS ITEM_QTY_6MO_SLS,
SUM(ITEM_QTY*FLAG_12MO) AS ITEM_QTY_12MO_SLS,
SUM(ITEM_QTY*FLAG_6MO*ONSALE_IND) AS ITEM_QTY_ONSALE_6MO_SLS,
SUM(ITEM_QTY*FLAG_12MO*ONSALE_IND) AS ITEM_QTY_ONSALE_12MO_SLS,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*FLAG_RTL)) +  COUNT(DISTINCT (ORDER_NUM_6MO)) AS NUM_TXNS_6MO_SLS,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*FLAG_RTL)) +  COUNT(DISTINCT (ORDER_NUM_12MO)) AS NUM_TXNS_12MO_SLS,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*FLAG_RTL*PLCC_TXN)) + COUNT(DISTINCT (ORDER_NUM_PLCC_6MO)) AS NUM_TXNS_PLCC_6MO_SLS,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*FLAG_RTL*PLCC_TXN)) + COUNT(DISTINCT (ORDER_NUM_PLCC_12MO)) AS NUM_TXNS_PLCC_12MO_SLS
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE BRAND='${hiveconf:CURRENT_BRAND}' AND GROSS_SALES_AMT > 0 AND ITEM_QTY > 0
GROUP BY CUSTOMER_KEY;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_2
AS SELECT 
CUSTOMER_KEY,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) AS NET_SALES_AMT_6MO_SLS_RTL,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) AS NET_SALES_AMT_12MO_SLS_RTL,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_6MO_SLS_RTL,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_12MO_SLS_RTL,
SUM(DISCOUNT_AMT*FLAG_6MO) AS DISCOUNT_AMT_6MO_SLS_RTL, 
SUM(DISCOUNT_AMT*FLAG_12MO) AS DISCOUNT_AMT_12MO_SLS_RTL, 
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) - NVL(SUM(TOT_PRD_CST_AMT*FLAG_6MO),0)AS NET_MARGIN_6MO_SLS_RTL,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) - NVL(SUM(TOT_PRD_CST_AMT*FLAG_12MO),0)AS NET_MARGIN_12MO_SLS_RTL,
SUM(ITEM_QTY*FLAG_6MO) AS ITEM_QTY_6MO_SLS_RTL,
SUM(ITEM_QTY*FLAG_12MO) AS ITEM_QTY_12MO_SLS_RTL,
SUM(ITEM_QTY*FLAG_6MO*ONSALE_IND) AS ITEM_QTY_ONSALE_6MO_SLS_RTL,
SUM(ITEM_QTY*FLAG_12MO*ONSALE_IND) AS ITEM_QTY_ONSALE_12MO_SLS_RTL,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO)) AS NUM_TXNS_6MO_SLS_RTL,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO)) AS NUM_TXNS_12MO_SLS_RTL,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*PLCC_TXN)) AS NUM_TXNS_PLCC_6MO_SLS_RTL,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*PLCC_TXN)) AS NUM_TXNS_PLCC_12MO_SLS_RTL
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE BRAND='${hiveconf:CURRENT_BRAND}' AND GROSS_SALES_AMT > 0 AND ITEM_QTY > 0 AND FLAG_RTL = 1
GROUP BY CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_3;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_3
AS SELECT 
CUSTOMER_KEY,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) AS NET_SALES_AMT_6MO_SLS_ONL,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) AS NET_SALES_AMT_12MO_SLS_ONL,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_6MO_SLS_ONL,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_12MO_SLS_ONL,
SUM(DISCOUNT_AMT*FLAG_6MO) AS DISCOUNT_AMT_6MO_SLS_ONL, 
SUM(DISCOUNT_AMT*FLAG_12MO) AS DISCOUNT_AMT_12MO_SLS_ONL, 
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) - NVL(SUM(TOT_PRD_CST_AMT*FLAG_6MO),0)AS NET_MARGIN_6MO_SLS_ONL,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) - NVL(SUM(TOT_PRD_CST_AMT*FLAG_12MO),0)AS NET_MARGIN_12MO_SLS_ONL,
SUM(ITEM_QTY*FLAG_6MO) AS ITEM_QTY_6MO_SLS_ONL,
SUM(ITEM_QTY*FLAG_12MO) AS ITEM_QTY_12MO_SLS_ONL,
SUM(ITEM_QTY*FLAG_6MO*ONSALE_IND) AS ITEM_QTY_ONSALE_6MO_SLS_ONL,
SUM(ITEM_QTY*FLAG_12MO*ONSALE_IND) AS ITEM_QTY_ONSALE_12MO_SLS_ONL,
COUNT(DISTINCT (ORDER_NUM_6MO)) AS NUM_TXNS_6MO_SLS_ONL,
COUNT(DISTINCT (ORDER_NUM_12MO)) AS NUM_TXNS_12MO_SLS_ONL,
COUNT(DISTINCT (ORDER_NUM_PLCC_6MO)) AS NUM_TXNS_PLCC_6MO_SLS_ONL,
COUNT(DISTINCT (ORDER_NUM_PLCC_12MO)) AS NUM_TXNS_PLCC_12MO_SLS_ONL
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE BRAND='${hiveconf:CURRENT_BRAND}' AND GROSS_SALES_AMT > 0 AND ITEM_QTY > 0 AND FLAG_ONL = 1
GROUP BY CUSTOMER_KEY;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_4;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_4
AS SELECT 
CUSTOMER_KEY,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0)) AS NET_SALES_AMT_6MO_RTN,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0)) AS NET_SALES_AMT_12MO_RTN,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*FLAG_RTL),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*FLAG_RTL),0)) AS NET_SALES_AMT_6MO_RTN_RTL,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*FLAG_RTL),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*FLAG_RTL),0)) AS NET_SALES_AMT_12MO_RTN_RTL,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*FLAG_ONL),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*FLAG_ONL),0)) AS NET_SALES_AMT_6MO_RTN_ONL,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*FLAG_ONL),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*FLAG_ONL),0)) AS NET_SALES_AMT_12MO_RTN_ONL,
-(SUM(ITEM_QTY*FLAG_6MO)) AS ITEM_QTY_6MO_RTN,
-(SUM(ITEM_QTY*FLAG_12MO)) AS ITEM_QTY_12MO_RTN,
-(SUM(ITEM_QTY*FLAG_6MO*FLAG_RTL)) AS ITEM_QTY_6MO_RTN_RTL,
-(SUM(ITEM_QTY*FLAG_12MO*FLAG_RTL)) AS ITEM_QTY_12MO_RTN_RTL,
-(SUM(ITEM_QTY*FLAG_6MO*FLAG_ONL)) AS ITEM_QTY_6MO_RTN_ONL,
-(SUM(ITEM_QTY*FLAG_12MO*FLAG_ONL)) AS ITEM_QTY_12MO_RTN_ONL,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*FLAG_RTL)) +  COUNT(DISTINCT (ORDER_NUM_6MO)) AS NUM_TXNS_6MO_RTN,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*FLAG_RTL)) +  COUNT(DISTINCT (ORDER_NUM_12MO)) AS NUM_TXNS_12MO_RTN,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*FLAG_RTL)) AS NUM_TXNS_6MO_RTN_RTL,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*FLAG_RTL)) AS NUM_TXNS_12MO_RTN_RTL,
COUNT(DISTINCT (ORDER_NUM_6MO)) AS NUM_TXNS_6MO_RTN_ONL,
COUNT(DISTINCT (ORDER_NUM_12MO)) AS NUM_TXNS_12MO_RTN_ONL
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE BRAND='${hiveconf:CURRENT_BRAND}' AND GROSS_SALES_AMT < 0 AND ITEM_QTY < 0
GROUP BY CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_5;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_5 
AS SELECT
CUSTOMER_KEY,       
SUM(SHIP_AMOUNT*FLAG_6MO) AS SHIP_AMOUNT_6MO_SLS_CP, 
SUM(GROSS_SALES_AMT*FLAG_6MO) AS GROSS_SALES_AMT_6MO_SLS_CP,
SUM(DISCOUNT_AMT*FLAG_6MO) AS DISCOUNT_AMT_6MO_SLS_CP, 
SUM(TOT_PRD_CST_AMT*FLAG_6MO) AS TOT_PRD_CST_AMT_6MO_SLS_CP,
SUM(ITEM_QTY*FLAG_6MO) AS ITEM_QTY_6MO_SLS_CP,
SUM(SHIP_AMOUNT*FLAG_12MO) AS SHIP_AMOUNT_12MO_SLS_CP, 
SUM(GROSS_SALES_AMT*FLAG_12MO) AS GROSS_SALES_AMT_12MO_SLS_CP,
SUM(DISCOUNT_AMT*FLAG_12MO) AS DISCOUNT_AMT_12MO_SLS_CP, 
SUM(TOT_PRD_CST_AMT*FLAG_12MO) AS TOT_PRD_CST_AMT_12MO_SLS_CP,
SUM(ITEM_QTY*FLAG_12MO) AS ITEM_QTY_12MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*FLAG_RTL)) +  COUNT(DISTINCT (ORDER_NUM_6MO)) AS NUM_TXNS_6MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*FLAG_RTL)) +  COUNT(DISTINCT (ORDER_NUM_12MO)) AS NUM_TXNS_12MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*FLAG_RTL*PLCC_TXN)) + COUNT(DISTINCT (ORDER_NUM_PLCC_6MO)) AS NUM_PLCC_TXNS_6MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*FLAG_RTL*PLCC_TXN)) + COUNT(DISTINCT (ORDER_NUM_PLCC_12MO)) AS NUM_PLCC_TXNS_12MO_SLS_CP
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE TRANSACTION_TYPE_CD IN ('S','M')
GROUP BY CUSTOMER_KEY;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_5;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_5 
AS SELECT
CUSTOMER_KEY,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0) AS NET_SALES_AMT_6MO_SLS_CP,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0) AS NET_SALES_AMT_12MO_SLS_CP,
NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_6MO_SLS_CP,
NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*PLCC_TXN),0) AS NET_SALES_AMT_PLCC_12MO_SLS_CP,
SUM(ITEM_QTY*FLAG_6MO) AS ITEM_QTY_6MO_SLS_CP,
SUM(ITEM_QTY*FLAG_12MO) AS ITEM_QTY_12MO_SLS_CP,
SUM(ITEM_QTY*FLAG_6MO*ONSALE_IND) AS ITEM_QTY_ONSALE_6MO_SLS_CP,
SUM(ITEM_QTY*FLAG_12MO*ONSALE_IND) AS ITEM_QTY_ONSALE_12MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO)) AS NUM_TXNS_6MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO)) AS NUM_TXNS_12MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*PLCC_TXN)) AS NUM_TXNS_PLCC_6MO_SLS_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*PLCC_TXN)) AS NUM_TXNS_PLCC_12MO_SLS_CP
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE GROSS_SALES_AMT > 0 AND ITEM_QTY > 0
GROUP BY CUSTOMER_KEY;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_6;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_6
AS SELECT
CUSTOMER_KEY,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_6MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO),0)) AS NET_SALES_AMT_6MO_RTN_CP,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_12MO),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO),0)) AS NET_SALES_AMT_12MO_RTN_CP,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_6MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_6MO*PLCC_TXN),0)) AS NET_SALES_AMT_PLCC_6MO_RTN_CP,
-(NVL(SUM(GROSS_SALES_AMT*FLAG_12MO*PLCC_TXN),0) + NVL(SUM(DISCOUNT_AMT*FLAG_12MO*PLCC_TXN),0)) AS NET_SALES_AMT_PLCC_12MO_RTN_CP,
-(SUM(ITEM_QTY*FLAG_6MO)) AS ITEM_QTY_6MO_RTN_CP,
-(SUM(ITEM_QTY*FLAG_12MO)) AS ITEM_QTY_12MO_RTN_CP,
-(SUM(ITEM_QTY*FLAG_6MO*ONSALE_IND)) AS ITEM_QTY_ONSALE_6MO_RTN_CP,
-(SUM(ITEM_QTY*FLAG_12MO*ONSALE_IND)) AS ITEM_QTY_ONSALE_12MO_RTN_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO)) AS NUM_TXNS_6MO_RTN_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO)) AS NUM_TXNS_12MO_RTN_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_6MO*PLCC_TXN)) AS NUM_TXNS_PLCC_6MO_RTN_CP,
COUNT(DISTINCT (TRANSACTION_NUM*FLAG_12MO*PLCC_TXN)) AS NUM_TXNS_PLCC_12MO_RTN_CP
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3
WHERE GROSS_SALES_AMT < 0 AND ITEM_QTY < 0
GROUP BY CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_LAST_PUR;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_LAST_PUR AS SELECT 
T3.CUSTOMER_KEY, 
DATEDIFF(T2.MAXDATE, T3.LAST_PUR_DT_CP) AS DAYS_LAST_PUR_CP,
DATEDIFF(T2.MAXDATE, T4.LAST_PUR_DT) AS DAYS_LAST_PUR,
DATEDIFF(T2.MAXDATE, T4.LAST_PUR_DT_RTL) AS DAYS_LAST_PUR_RTL,
DATEDIFF(T2.MAXDATE, T4.LAST_PUR_DT_ONL) AS DAYS_LAST_PUR_ONL
FROM
(
SELECT T1.CUSTOMER_KEY, MAX(T1.ORDER_DATE) AS LAST_PUR_DT_CP
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3 T1 
WHERE 
GROSS_SALES_AMT > 0  AND ITEM_QTY > 0
GROUP BY T1.CUSTOMER_KEY
) T3
LEFT OUTER JOIN
(
SELECT T1.CUSTOMER_KEY, 
MAX(T1.ORDER_DATE) AS LAST_PUR_DT,
TO_DATE(FROM_UNIXTIME(MAX(UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') * T1.FLAG_RTL))) AS LAST_PUR_DT_RTL,
TO_DATE(FROM_UNIXTIME(MAX(UNIX_TIMESTAMP(T1.ORDER_DATE, 'yyyy-MM-dd') * T1.FLAG_ONL))) AS LAST_PUR_DT_ONL
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3 T1
WHERE 
GROSS_SALES_AMT > 0  AND ITEM_QTY > 0 AND
${hiveconf:CURRENT_BRAND}_FLAG=1
GROUP BY T1.CUSTOMER_KEY
) T4
ON
T3.CUSTOMER_KEY = T4.CUSTOMER_KEY
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_ON_BOOKS;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_ON_BOOKS 
AS SELECT 
T4.CUSTOMER_KEY,
DATEDIFF(T5.MAXDATE, T4.ACQUISITION_DATE_CP) AS DAYS_ON_BOOKS_CP,
DATEDIFF(T5.MAXDATE, T4.ACQUISITION_DATE) AS DAYS_ON_BOOKS
FROM
(
SELECT
T1.CUSTOMER_KEY,
T2.ACQUISITION_DATE_CP,
T3.ACQUISITION_DATE
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN
(
SELECT 
CUST_KEY AS CUSTOMER_KEY,
TO_DATE(MIN(ACQUISITION_DATE)) AS ACQUISITION_DATE_CP
FROM MDS_NEW.ODS_BRAND_CUSTOMER_T 
GROUP BY CUST_KEY
) T2
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
LEFT OUTER JOIN
(
SELECT 
CUST_KEY AS CUSTOMER_KEY,
TO_DATE(MIN(ACQUISITION_DATE)) AS ACQUISITION_DATE
FROM MDS_NEW.ODS_BRAND_CUSTOMER_T 
WHERE BRAND='${hiveconf:CURRENT_BRAND}'
GROUP BY CUST_KEY
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
) T4
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T5;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.CAMPAIGN_VERSION) AS EMAILS_CLICKED
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CAMPAIGN_VERSION, CELL_KEY, URL_KEY, CLICK_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_EMAILCLICKS_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CELL_T T4
ON T3.CELL_KEY = T4.CELL_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CAMPAIGN_T T5
ON T4.CAMPAIGN_ID = T5.CAMPAIGN_ID
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
WHERE
UNIX_TIMESTAMP(TO_DATE(T3.CLICK_DATE), 'yyyy-MM-dd') BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd') AND
T3.COUNTRY='${hiveconf:CURRENT_COUNTRY}' AND 
T3.BRAND='${hiveconf:CURRENT_BRAND}' AND 
T5.CAMPAIGN_OBJECTIVE != 'T'
GROUP BY T1.CUSTOMER_KEY;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.CAMPAIGN_VERSION) AS EMAILS_CLICKED_CP
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CAMPAIGN_VERSION, CELL_KEY, URL_KEY, CLICK_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_EMAILCLICKS_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CELL_T T4
ON T3.CELL_KEY = T4.CELL_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CAMPAIGN_T T5
ON T4.CAMPAIGN_ID = T5.CAMPAIGN_ID
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
WHERE
UNIX_TIMESTAMP(TO_DATE(T3.CLICK_DATE), 'yyyy-MM-dd') BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd') AND
T3.COUNTRY='${hiveconf:CURRENT_COUNTRY}' AND 
T5.CAMPAIGN_OBJECTIVE != 'T'
GROUP BY T1.CUSTOMER_KEY;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILCLICKS;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILCLICKS
AS SELECT 
T2.CUSTOMER_KEY, T1.EMAILS_CLICKED, T2.EMAILS_CLICKED_CP
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T2
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1 T1
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;







DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.CAMPAIGN_VERSION) AS EMAILS_OPENED
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CAMPAIGN_VERSION, CELL_KEY, EVENT_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_EMAILOPENS_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CELL_T T4
ON T3.CELL_KEY = T4.CELL_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CAMPAIGN_T T5
ON T4.CAMPAIGN_ID = T5.CAMPAIGN_ID
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
WHERE
UNIX_TIMESTAMP(TO_DATE(T3.EVENT_DATE), 'yyyy-MM-dd') BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd') AND
T3.COUNTRY='${hiveconf:CURRENT_COUNTRY}' AND 
T3.BRAND='${hiveconf:CURRENT_BRAND}' AND 
T5.CAMPAIGN_OBJECTIVE != 'T'
GROUP BY T1.CUSTOMER_KEY;






DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.CAMPAIGN_VERSION) AS EMAILS_OPENED_CP
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CAMPAIGN_VERSION, CELL_KEY, EVENT_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_EMAILOPENS_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CELL_T T4
ON T3.CELL_KEY = T4.CELL_KEY
LEFT OUTER JOIN
MDS_NEW.ODS_CAMPAIGN_T T5
ON T4.CAMPAIGN_ID = T5.CAMPAIGN_ID
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
WHERE
UNIX_TIMESTAMP(TO_DATE(T3.EVENT_DATE), 'yyyy-MM-dd') BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd') AND
T3.COUNTRY='${hiveconf:CURRENT_COUNTRY}' AND 
T5.CAMPAIGN_OBJECTIVE != 'T'
GROUP BY T1.CUSTOMER_KEY;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILOPENS;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILOPENS
AS SELECT 
T2.CUSTOMER_KEY, T1.EMAILS_OPENED, T2.EMAILS_OPENED_CP
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T2
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1 T1
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;











CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.TEMP AS SELECT T1.*
FROM 
MDS_NEW.ODS_MAILINGEMAIL_T T1
INNER JOIN
MDS_NEW.ODS_CELL_T T2
ON T1.CELL_KEY = T2.CELL_KEY
INNER JOIN
MDS_NEW.ODS_CAMPAIGN_T T3
ON T2.CAMPAIGN_ID = T3.CAMPAIGN_ID
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T4
WHERE 
T1.BRAND = '${hiveconf:CURRENT_BRAND}' AND
T3.CAMPAIGN_OBJECTIVE != 'T' AND 
T3.COUNTRY = '${hiveconf:CURRENT_COUNTRY}' AND
(
UNIX_TIMESTAMP(TO_DATE(T1.EVENT_DATE), 'yyyy-MM-dd') >= UNIX_TIMESTAMP(T4.MINDATE, 'yyyy-MM-dd') AND
UNIX_TIMESTAMP(TO_DATE(T1.EVENT_DATE), 'yyyy-MM-dd') <= UNIX_TIMESTAMP(T4.MAXDATE, 'yyyy-MM-dd')
);


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 AS 
SELECT
CUSTOMER_KEY, CAMPAIGN_VERSION,
COUNT(DISTINCT CAMPAIGN_VERSION) AS EMAILS_RECEIVED_12MO,
TO_DATE(MIN(EVENT_DATE)) AS EVENT_DATE
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1
GROUP BY CUSTOMER_KEY, CAMPAIGN_VERSION;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST3;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST3 AS SELECT 
T1.CUSTOMER_KEY, 
T1.CAMPAIGN_VERSION, 
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,
T1.EVENT_DATE, 
COUNT(DISTINCT T2.ORDER_DATE) AS RESPONSES,
COUNT(DISTINCT(TRANSACTION_NUM*FLAG_12MO*FLAG_RTL)) + COUNT(DISTINCT(ORDER_NUM_12MO)) AS NUM_TXNS_SLS_PROMO_12MO,
SUM(GROSS_SALES_AMT) AS GROSS_SALES_SLS_PROMO_12MO,
SUM(DISCOUNT_AMT) AS DISCOUNT_SLS_PROMO_12MO,
(
CASE WHEN COUNT(DISTINCT T2.ORDER_DATE) > 0 THEN 1 ELSE NULL END
) AS RESPONSE_FLAG 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3 T2
ON T2.CUSTOMER_KEY=T1.CUSTOMER_KEY
WHERE
UNIX_TIMESTAMP(T2.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(TO_DATE(T1.GAP_CAMPAIGN_START_DATE), 'yyyy-MM-dd') AND
UNIX_TIMESTAMP(T2.ORDER_DATE, 'yyyy-MM-dd') <= UNIX_TIMESTAMP(TO_DATE(T1.GAP_CAMPAIGN_END_DATE), 'yyyy-MM-dd') AND
T2.BRAND='${hiveconf:CURRENT_BRAND}' AND 
T2.TRANSACTION_TYPE_CD IN ('S','M')
GROUP BY
T1.CUSTOMER_KEY, 
T1.CAMPAIGN_ID, 
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO, 
T1.GAP_CAMPAIGN_START_DATE, 
T1.GAP_CAMPAIGN_END_DATE;




CREATE TABLE TEMP AS SELECT CUSTOMER_KEY, 

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1 AS SELECT DISTINCT
T1.CUSTOMER_KEY, T3.CAMPAIGN_ID, T2.CELL_KEY, 
T3.GAP_CELL_START_DATE, T3.GAP_CELL_END_DATE
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
INNER JOIN
MDS_NEW.ODS_MAILINGMAILHOUSE_T T2
ON T1.CUSTOMER_KEY=T2.CUSTOMER_KEY
INNER JOIN
MDS_NEW.ODS_CELL_T T3
ON T2.CELL_KEY = T3.CELL_KEY
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T4
INNER JOIN
MDS_NEW.ODS_CAMPAIGN_T T5
ON T3.CAMPAIGN_ID = T5.CAMPAIGN_ID
WHERE 
T2.EVENT_TYPE='M' AND
(
UNIX_TIMESTAMP(T3.GAP_CELL_START_DATE, 'yyyy-MM-dd_HH-mm-ss_Z') BETWEEN
UNIX_TIMESTAMP(T4.MINDATE, 'yyyy-MM-dd') AND
UNIX_TIMESTAMP(T4.MAXDATE, 'yyyy-MM-dd') AND
) AND
T5.GAP_CAMPAIGN_BRAND = '${hiveconf:CURRENT_BRAND}' AND T5.COUNTRY = '${hiveconf:CURRENT_COUNTRY}'
;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 AS 
SELECT
CUSTOMER_KEY, CAMPAIGN_ID,
COUNT(DISTINCT CELL_KEY) AS ${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,
MIN(GAP_CELL_START_DATE) AS GAP_CAMPAIGN_START_DATE,
MAX(GAP_CELL_END_DATE) AS GAP_CAMPAIGN_END_DATE
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1
GROUP BY CUSTOMER_KEY, CAMPAIGN_ID;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST3;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST3 AS SELECT 
T1.CUSTOMER_KEY, 
T1.CAMPAIGN_ID, 
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,
T1.GAP_CAMPAIGN_START_DATE, 
T1.GAP_CAMPAIGN_END_DATE,
COUNT(DISTINCT T2.ORDER_DATE) AS RESPONSES,
COUNT(DISTINCT(TRANSACTION_NUM*FLAG_12MO*FLAG_RTL)) + COUNT(DISTINCT(ORDER_NUM_12MO)) AS NUM_TXNS_SLS_PROMO_12MO,
SUM(GROSS_SALES_AMT) AS GROSS_SALES_SLS_PROMO_12MO,
SUM(DISCOUNT_AMT) AS DISCOUNT_SLS_PROMO_12MO,
(
CASE WHEN COUNT(DISTINCT T2.ORDER_DATE) > 0 THEN 1 ELSE NULL END
) AS RESPONSE_FLAG 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3 T2
ON T2.CUSTOMER_KEY=T1.CUSTOMER_KEY
WHERE
UNIX_TIMESTAMP(T2.ORDER_DATE, 'yyyy-MM-dd') >= UNIX_TIMESTAMP(TO_DATE(T1.GAP_CAMPAIGN_START_DATE), 'yyyy-MM-dd') AND
UNIX_TIMESTAMP(T2.ORDER_DATE, 'yyyy-MM-dd') <= UNIX_TIMESTAMP(TO_DATE(T1.GAP_CAMPAIGN_END_DATE), 'yyyy-MM-dd') AND
T2.BRAND='${hiveconf:CURRENT_BRAND}' AND 
T2.TRANSACTION_TYPE_CD IN ('S','M')
GROUP BY
T1.CUSTOMER_KEY, 
T1.CAMPAIGN_ID, 
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO, 
T1.GAP_CAMPAIGN_START_DATE, 
T1.GAP_CAMPAIGN_END_DATE;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST4;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST4 AS SELECT
T1.CUSTOMER_KEY, 
T1.CAMPAIGN_ID, 
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,
T1.GAP_CAMPAIGN_START_DATE, 
T1.GAP_CAMPAIGN_END_DATE,
T2.RESPONSES,
T2.NUM_TXNS_SLS_PROMO_12MO,
T2.GROSS_SALES_SLS_PROMO_12MO,
T2.DISCOUNT_SLS_PROMO_12MO,
T2.RESPONSE_FLAG
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T1
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST3 T2
ON
(
(T1.CUSTOMER_KEY = T2.CUSTOMER_KEY) AND
(T1.CAMPAIGN_ID = T2.CAMPAIGN_ID)
);



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST5;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST5 AS SELECT
CUSTOMER_KEY, 
COUNT(CAMPAIGN_ID) AS ${hiveconf:CURRENT_BRAND}_CAMPAIGNS_RECEIVED_12MO,
SUM(COALESCE(${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,0)) AS ${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,
SUM(COALESCE(RESPONSE_FLAG,0)) AS ${hiveconf:CURRENT_BRAND}_PROMOTIONS_RESPONDED_12MO,
SUM(COALESCE(RESPONSES,0)) AS RESPONSES, 
SUM(COALESCE(NUM_TXNS_SLS_PROMO_12MO,0)) AS NUM_TXNS_SLS_PROMO_12MO,
SUM(COALESCE(GROSS_SALES_SLS_PROMO_12MO,0)) AS GROSS_SALES_SLS_PROMO_12MO,
SUM(COALESCE(DISCOUNT_SLS_PROMO_12MO,0)) AS DISCOUNT_SLS_PROMO_12MO,
SUM(COALESCE(GROSS_SALES_SLS_PROMO_12MO,0)) + SUM(COALESCE(DISCOUNT_SLS_PROMO_12MO,0)) AS NET_SALES_SLS_PROMO_12MO
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST4
GROUP BY CUSTOMER_KEY;   

SELECT * FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST5 LIMIT 30;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_PROMOTIONS_P365;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_PROMOTIONS_P365 AS SELECT 
CUSTOMER_KEY, ${hiveconf:CURRENT_BRAND}_CAMPAIGNS_RECEIVED_12MO, ${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO, ${hiveconf:CURRENT_BRAND}_PROMOTIONS_RESPONDED_12MO, 
${hiveconf:CURRENT_BRAND}_PROMOTIONS_RESPONDED_12MO / ${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO AS RESPONSE_RATE_12MO,
NUM_TXNS_SLS_PROMO_12MO, GROSS_SALES_SLS_PROMO_12MO, DISCOUNT_SLS_PROMO_12MO,
NET_SALES_SLS_PROMO_12MO
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST5;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST3;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST4;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST5;






DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.URL_KEY) AS EMAILS_CLICKED_${hiveconf:CURRENT_BRAND}
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
INNER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CELL_KEY, URL_KEY, CLICK_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_EMAILCLICKS_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
WHERE
UNIX_TIMESTAMP(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(T3.CLICK_DATE,' ')[0],'MM/dd/yyyy'))), 'yyyy-MM-dd')
BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd')
AND T3.COUNTRY='US' AND T3.BRAND='${hiveconf:CURRENT_BRAND}'
GROUP BY T1.CUSTOMER_KEY;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.URL_KEY) AS EMAILS_CLICKED_CP
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
INNER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CELL_KEY, URL_KEY, CLICK_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_EMAILCLICKS_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
WHERE
UNIX_TIMESTAMP(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(T3.CLICK_DATE,' ')[0],'MM/dd/yyyy'))), 'yyyy-MM-dd')
BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd')
AND T3.COUNTRY='US'
GROUP BY T1.CUSTOMER_KEY;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILCLICKS;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILCLICKS
AS SELECT 
T2.CUSTOMER_KEY, T1.EMAILS_CLICKED_${hiveconf:CURRENT_BRAND}, T2.EMAILS_CLICKED_CP
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T2
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1 T1
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.CELL_KEY) AS EMAILS_VIEWED_${hiveconf:CURRENT_BRAND}
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
INNER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CELL_KEY, EVENT_TYPE, EVENT_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_MAILINGEMAIL_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
WHERE
UNIX_TIMESTAMP(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(T3.EVENT_DATE,' ')[0],'MM/dd/yyyy'))), 'yyyy-MM-dd')
BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd')
AND T3.COUNTRY='US' AND T3.BRAND='${hiveconf:CURRENT_BRAND}' AND T3.EVENT_TYPE='V'
GROUP BY T1.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2
AS SELECT T1.CUSTOMER_KEY, COUNT(DISTINCT T3.CELL_KEY) AS EMAILS_VIEWED_CP
FROM 
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
INNER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE T2
INNER JOIN
(
SELECT DISTINCT CUSTOMER_KEY, CELL_KEY, EVENT_TYPE, EVENT_DATE, COUNTRY, BRAND
FROM
MDS_NEW.ODS_MAILINGEMAIL_T
) T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
WHERE
UNIX_TIMESTAMP(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(T3.EVENT_DATE,' ')[0],'MM/dd/yyyy'))), 'yyyy-MM-dd')
BETWEEN
UNIX_TIMESTAMP(T2.MINDATE, 'yyyy-MM-dd') AND UNIX_TIMESTAMP(T2.MAXDATE, 'yyyy-MM-dd')
AND T3.COUNTRY='US' AND T3.EVENT_TYPE='V'
GROUP BY T1.CUSTOMER_KEY;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILVIEWS;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILVIEWS
AS SELECT 
T2.CUSTOMER_KEY, T1.EMAILS_VIEWED_${hiveconf:CURRENT_BRAND}, T2.EMAILS_VIEWED_CP
FROM
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2 T2
LEFT OUTER JOIN
${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1 T1
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST1;
DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TEST2;







DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_1 AS SELECT 
T3.*, 
T4.MDSE_DIV_DESC 
FROM
(
SELECT
T1.*, 
T2.FLAG_12MO, 
T2.FLAG_6MO, 
T2.ORDER_DATE
FROM MDS_NEW.ODS_ORDERLINE_T T1
INNER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3 T2
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY AND T1.TRANSACTION_NUM = T2.TRANSACTION_NUM
WHERE
T2.BRAND = '${hiveconf:CURRENT_BRAND}' AND T2.TRANSACTION_TYPE_CD IN ('S','M') AND T1.SALES_AMT > 0
) T3
LEFT OUTER JOIN MDS_NEW.ODS_PRODUCT_T T4
ON T3.PRODUCT_KEY = T4.PRODUCT_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_TXN_P365_${hiveconf:CAMPAIGN_VERSION}_3;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_2 AS SELECT       
(
CASE
WHEN T1.ON_SALE_FLAG='Y' THEN 1
ELSE NULL
END
) AS ONSALE_IND, T1.*          
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_1 T1;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_1;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DIV_SHP;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DIV_SHP AS SELECT 
T1.CUSTOMER_KEY, COUNT(DISTINCT T1.MDSE_DIV_DESC_CORRECTED) AS DIV_SHP_${hiveconf:CURRENT_BRAND}
FROM 
(
SELECT DISTINCT CUSTOMER_KEY, MDSE_DIV_DESC,
(
 CASE 
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'ACCESS') > 0 THEN 'ACC'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'BABY') > 0 THEN 'BABY'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'BODY') > 0 THEN 'BODY'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'BOY') > 0 THEN 'BOYS'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'GAP1969') > 0 THEN 'GAP1969'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'MEN') > 0 THEN 'MENS'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'WOMEN') > 0 THEN 'WOMENS'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'GIRL') > 0 THEN 'GIRLS'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'KID') > 0 THEN 'KIDS'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'MATERNITY') > 0 THEN 'MAT'
WHEN INSTR(UPPER(MDSE_DIV_DESC), 'OUTLET') > 0 THEN 'OUTLET'
ELSE 'MISC'
END 
) AS MDSE_DIV_DESC_CORRECTED
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_2
) T1
GROUP BY T1.CUSTOMER_KEY;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_ON_SALE_PUR;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_ON_SALE_PUR AS SELECT
CUSTOMER_KEY, 
SUM(ONSALE_IND*ITEM_QTY*FLAG_12MO) AS ONSALE_QTY_12MO,
SUM(ONSALE_IND*ITEM_QTY*FLAG_6MO) AS ONSALE_QTY_6MO
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_2
GROUP BY CUSTOMER_KEY;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_ORDLN_P365_${hiveconf:CAMPAIGN_VERSION}_2;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_1;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_1 AS SELECT
T1.CUSTOMER_KEY, T3.START_DT, T3.END_DT, T2.OPEN_DATE, 
T2.REISSUE_DATE, T2.BRAND, T2.PLATE_CODE, T2.MARKETABILITY,
T2.PLCC_DROPPED, T2.EST_CLOSED_DT, T2.CARD_TYP
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN 
MDS_NEW.ODS_PLCC_CARDHOLDER_T T2
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
INNER JOIN
(
SELECT
TO_DATE(MIN(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(EVENT_DATE,' ')[0],'MM/dd/yyyy')))) AS START_DT, 
DATE_ADD(TO_DATE(MIN(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(EVENT_DATE,' ')[0],'MM/dd/yyyy')))), 1) AS END_DT 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED
) T3
WHERE 
TO_DATE(T2.OPEN_DATE) <= DATE_SUB(TO_DATE(T3.START_DT), 15) AND 
(
TO_DATE(EST_CLOSED_DT) IS NULL OR 
TO_DATE(EST_CLOSED_DT) >= DATE_SUB(TO_DATE(T3.START_DT), 15)
);


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_2;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_2 AS SELECT
T1.CUSTOMER_KEY, T1.START_DT, T1.END_DT, T1.BRAND, T1.PLATE_CODE, T1.CARD_TYP,
MAX(T1.OPEN_DATE) AS OPEN_DATE, MAX(T1.REISSUE_DATE) AS REISSUE_DATE, MAX(T1.EST_CLOSED_DT) AS EST_CLOSED_DT
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_1 T1 
GROUP BY T1.CUSTOMER_KEY, T1.START_DT, T1.END_DT, T1.BRAND, T1.PLATE_CODE, T1.CARD_TYP;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_1;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_3;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_3 AS SELECT
T1.CUSTOMER_KEY, T1.START_DT, T1.END_DT, T1.BRAND, T1.PLATE_CODE, T1.CARD_TYP,  
T1.OPEN_DATE, T1.REISSUE_DATE,  T1.EST_CLOSED_DT,
(CASE WHEN BRAND='${hiveconf:CURRENT_BRAND}' AND PLATE_CODE<4 THEN 1 ELSE 0 END) BASIC_FLAG,
(CASE WHEN BRAND='${hiveconf:CURRENT_BRAND}' AND PLATE_CODE=4 THEN 1 ELSE 0 END) SILVER_FLAG,
(CASE WHEN BRAND<>'${hiveconf:CURRENT_BRAND}' THEN 1 ELSE 0 END) SISTER_FLAG
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_2 T1;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_2;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_4;             
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_4 AS SELECT
CUSTOMER_KEY, 
MAX(BASIC_FLAG) AS BASIC_FLAG,
MAX(SISTER_FLAG) AS SISTER_FLAG,
MAX(SILVER_FLAG) AS SILVER_FLAG
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_3
GROUP BY CUSTOMER_KEY;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_3; 


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_5; 
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_5 AS SELECT
T1.CUSTOMER_KEY, T2.BASIC_FLAG, T2.SILVER_FLAG, T2.SISTER_FLAG
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_4 T2
ON T1.CUSTOMER_KEY=T2.CUSTOMER_KEY;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_4;                    


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS;  
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS AS SELECT
CUSTOMER_KEY, BASIC_FLAG, SILVER_FLAG, SISTER_FLAG,
(
CASE 
WHEN VISASIG_FLAG = 1 THEN 1
WHEN SILVER_FLAG = 1 AND VISASIG_FLAG <> 1 THEN 2
WHEN BASIC_FLAG = 1 AND SILVER_FLAG <> 1 AND VISASIG_FLAG <> 1 THEN 3
WHEN SISTER_FLAG = 1 AND SILVER_FLAG <> 1 AND BASIC_FLAG <> 1 AND VISASIG_FLAG <> 1 THEN 4
ELSE 5
END
) AS CARD_STATUS
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_5;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS_5; 





DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TRANSACTIONS;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TRANSACTIONS AS
SELECT
T1.CUSTOMER_KEY,T1.GROSS_SALES_AMT,T1.DISCOUNT_AMT,T1.TOT_PRD_CST_AMT,T1.ITEM_QTY,T1.NET_SALES_AMT,T1.NUM_TXNS,T1.AVG_ORD_SZ,T1.RESPONDER,
T2.SHIP_AMOUNT_6MO_SLS,T2.GROSS_SALES_AMT_6MO_SLS,T2.DISCOUNT_AMT_6MO_SLS,T2.TOT_PRD_CST_AMT_6MO_SLS,T2.ITEM_QTY_6MO_SLS,T2.SHIP_AMOUNT_12MO_SLS,T2.GROSS_SALES_AMT_12MO_SLS,T2.DISCOUNT_AMT_12MO_SLS,T2.TOT_PRD_CST_AMT_12MO_SLS,T2.ITEM_QTY_12MO_SLS,T2.NUM_TXNS_6MO_SLS,T2.NUM_TXNS_12MO_SLS,T2.NUM_PLCC_TXNS_6MO_SLS,T2.NUM_PLCC_TXNS_12MO_SLS,
T3.GROSS_SALES_AMT_6MO_RTN,T3.DISCOUNT_AMT_6MO_RTN,T3.ITEM_QTY_6MO_RTN,T3.GROSS_SALES_AMT_12MO_RTN,T3.DISCOUNT_AMT_12MO_RTN,T3.ITEM_QTY_12MO_RTN,T3.NUM_TXNS_6MO_RTN,T3.NUM_TXNS_12MO_RTN,
T4.SHIP_AMOUNT_6MO_SLS_CP,T4.GROSS_SALES_AMT_6MO_SLS_CP,T4.DISCOUNT_AMT_6MO_SLS_CP,T4.TOT_PRD_CST_AMT_6MO_SLS_CP,T4.ITEM_QTY_6MO_SLS_CP,T4.SHIP_AMOUNT_12MO_SLS_CP,T4.GROSS_SALES_AMT_12MO_SLS_CP,T4.DISCOUNT_AMT_12MO_SLS_CP,T4.TOT_PRD_CST_AMT_12MO_SLS_CP,T4.ITEM_QTY_12MO_SLS_CP,T4.NUM_TXNS_6MO_SLS_CP,T4.NUM_TXNS_12MO_SLS_CP,T4.NUM_PLCC_TXNS_6MO_SLS_CP,T4.NUM_PLCC_TXNS_12MO_SLS_CP,
T5.GROSS_SALES_AMT_6MO_RTN_CP,T5.DISCOUNT_AMT_6MO_RTN_CP,T5.ITEM_QTY_6MO_RTN_CP,T5.GROSS_SALES_AMT_12MO_RTN_CP,T5.DISCOUNT_AMT_12MO_RTN_CP,T5.ITEM_QTY_12MO_RTN_CP,T5.NUM_TXNS_6MO_RTN_CP,T5.NUM_TXNS_12MO_RTN_CP,
T6.SHIP_AMOUNT_6MO_ONL_SLS,T6.GROSS_SALES_AMT_6MO_ONL_SLS,T6.DISCOUNT_AMT_6MO_ONL_SLS,T6.TOT_PRD_CST_AMT_6MO_ONL_SLS,T6.ITEM_QTY_6MO_ONL_SLS,T6.SHIP_AMOUNT_12MO_ONL_SLS,T6.GROSS_SALES_AMT_12MO_ONL_SLS,T6.DISCOUNT_AMT_12MO_ONL_SLS,T6.TOT_PRD_CST_AMT_12MO_ONL_SLS,T6.ITEM_QTY_12MO_ONL_SLS,T6.NUM_TXNS_6MO_ONL_SLS,T6.NUM_TXNS_12MO_ONL_SLS
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM T1
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_1 T2 
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_2 T3 
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_3 T4
ON T1.CUSTOMER_KEY = T4.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_4 T5 
ON T1.CUSTOMER_KEY = T5.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_5 T6 
ON T1.CUSTOMER_KEY = T6.CUSTOMER_KEY
;


DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED;
CREATE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED AS
SELECT
T1.CUSTOMER_KEY,T1.GROSS_SALES_AMT,T1.DISCOUNT_AMT,T1.TOT_PRD_CST_AMT,T1.ITEM_QTY,T1.NET_SALES_AMT,T1.NUM_TXNS,T1.AVG_ORD_SZ,T1.RESPONDER,
T1.SHIP_AMOUNT_6MO_SLS,T1.GROSS_SALES_AMT_6MO_SLS,T1.DISCOUNT_AMT_6MO_SLS,T1.TOT_PRD_CST_AMT_6MO_SLS,T1.ITEM_QTY_6MO_SLS,T1.SHIP_AMOUNT_12MO_SLS,T1.GROSS_SALES_AMT_12MO_SLS,T1.DISCOUNT_AMT_12MO_SLS,T1.TOT_PRD_CST_AMT_12MO_SLS,T1.ITEM_QTY_12MO_SLS,T1.NUM_TXNS_6MO_SLS,T1.NUM_TXNS_12MO_SLS,T1.NUM_PLCC_TXNS_6MO_SLS,T1.NUM_PLCC_TXNS_12MO_SLS,
T1.GROSS_SALES_AMT_6MO_RTN,T1.DISCOUNT_AMT_6MO_RTN,T1.ITEM_QTY_6MO_RTN,T1.GROSS_SALES_AMT_12MO_RTN,T1.DISCOUNT_AMT_12MO_RTN,T1.ITEM_QTY_12MO_RTN,T1.NUM_TXNS_6MO_RTN,T1.NUM_TXNS_12MO_RTN,
T1.SHIP_AMOUNT_6MO_SLS_CP,T1.GROSS_SALES_AMT_6MO_SLS_CP,T1.DISCOUNT_AMT_6MO_SLS_CP,T1.TOT_PRD_CST_AMT_6MO_SLS_CP,T1.ITEM_QTY_6MO_SLS_CP,T1.SHIP_AMOUNT_12MO_SLS_CP,T1.GROSS_SALES_AMT_12MO_SLS_CP,T1.DISCOUNT_AMT_12MO_SLS_CP,T1.TOT_PRD_CST_AMT_12MO_SLS_CP,T1.ITEM_QTY_12MO_SLS_CP,T1.NUM_TXNS_6MO_SLS_CP,T1.NUM_TXNS_12MO_SLS_CP,T1.NUM_PLCC_TXNS_6MO_SLS_CP,T1.NUM_PLCC_TXNS_12MO_SLS_CP,
T1.GROSS_SALES_AMT_6MO_RTN_CP,T1.DISCOUNT_AMT_6MO_RTN_CP,T1.ITEM_QTY_6MO_RTN_CP,T1.GROSS_SALES_AMT_12MO_RTN_CP,T1.DISCOUNT_AMT_12MO_RTN_CP,T1.ITEM_QTY_12MO_RTN_CP,T1.NUM_TXNS_6MO_RTN_CP,T1.NUM_TXNS_12MO_RTN_CP,
T1.SHIP_AMOUNT_6MO_ONL_SLS,T1.GROSS_SALES_AMT_6MO_ONL_SLS,T1.DISCOUNT_AMT_6MO_ONL_SLS,T1.TOT_PRD_CST_AMT_6MO_ONL_SLS,T1.ITEM_QTY_6MO_ONL_SLS,T1.SHIP_AMOUNT_12MO_ONL_SLS,T1.GROSS_SALES_AMT_12MO_ONL_SLS,T1.DISCOUNT_AMT_12MO_ONL_SLS,T1.TOT_PRD_CST_AMT_12MO_ONL_SLS,T1.ITEM_QTY_12MO_ONL_SLS,T1.NUM_TXNS_6MO_ONL_SLS,T1.NUM_TXNS_12MO_ONL_SLS,
T2.BASIC_FLAG,T2.SILVER_FLAG,T2.SISTER_FLAG,T2.CARD_STATUS,
T3.DAYS_LAST_PUR_CP,T3.DAYS_LAST_PUR_${hiveconf:CURRENT_BRAND},
T4.DAYS_ON_BOOKS_CP,
T5.DIV_SHP_${hiveconf:CURRENT_BRAND},
T6.ONSALE_QTY_12MO,T6.ONSALE_QTY_6MO,
T7.PROMOTIONS_RECEIVED_CP,T7.PROMOTIONS_RECEIVED_${hiveconf:CURRENT_BRAND},
T8.${hiveconf:CURRENT_BRAND}_CAMPAIGNS_RECEIVED_12MO,T8.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,T8.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RESPONDED_12MO,T8.RESPONSE_RATE_12MO,T8.NUM_TXNS_SLS_PROMO_12MO,T8.GROSS_SALES_SLS_PROMO_12MO,T8.DISCOUNT_SLS_PROMO_12MO,T8.NET_SALES_SLS_PROMO_12MO,
T9.EMAILS_CLICKED_${hiveconf:CURRENT_BRAND}, T9.EMAILS_CLICKED_CP,
T10.EMAILS_VIEWED_${hiveconf:CURRENT_BRAND}, T10.EMAILS_VIEWED_CP,
T11.START_DT, T11.END_DT
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TRANSACTIONS T1
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS T2 
ON T1.CUSTOMER_KEY = T2.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_LAST_PUR T3
ON T1.CUSTOMER_KEY = T3.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_ON_BOOKS_CP T4
ON T1.CUSTOMER_KEY = T4.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DIV_SHP T5
ON T1.CUSTOMER_KEY = T5.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_ON_SALE_PUR T6
ON T1.CUSTOMER_KEY = T6.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_PROMO_RECEIVED T7
ON T1.CUSTOMER_KEY = T7.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_PROMOTIONS_P365 T8 
ON T1.CUSTOMER_KEY = T8.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILCLICKS T9
ON T1.CUSTOMER_KEY = T9.CUSTOMER_KEY
LEFT OUTER JOIN ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILVIEWS T10
ON T1.CUSTOMER_KEY = T10.CUSTOMER_KEY
INNER JOIN
(
SELECT 
TO_DATE(MIN(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(EVENT_DATE,' ')[0],'MM/dd/yyyy')))) AS START_DT, 
DATE_ADD(TO_DATE(MIN(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(EVENT_DATE,' ')[0],'MM/dd/yyyy')))), 1) AS END_DT 
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_MAILED
) T11
;



DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED_TXT;
CREATE EXTERNAL TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED_TXT
(
CUSTOMER_KEY INT,
GROSS_SALES_AMT DOUBLE,
DISCOUNT_AMT DOUBLE,
TOT_PRD_CST_AMT DOUBLE,
ITEM_QTY BIGINT,
NET_SALES_AMT DOUBLE,
NUM_TXNS BIGINT,
AVG_ORD_SZ DOUBLE,
RESPONDER INT,
SHIP_AMOUNT_6MO_SLS DOUBLE,
GROSS_SALES_AMT_6MO_SLS DOUBLE,
DISCOUNT_AMT_6MO_SLS DOUBLE,
TOT_PRD_CST_AMT_6MO_SLS DOUBLE,
ITEM_QTY_6MO_SLS BIGINT,
SHIP_AMOUNT_12MO_SLS DOUBLE,
GROSS_SALES_AMT_12MO_SLS DOUBLE,
DISCOUNT_AMT_12MO_SLS DOUBLE,
TOT_PRD_CST_AMT_12MO_SLS DOUBLE,
ITEM_QTY_12MO_SLS BIGINT,
NUM_TXNS_6MO_SLS BIGINT,
NUM_TXNS_12MO_SLS BIGINT,
NUM_PLCC_TXNS_6MO_SLS BIGINT,
NUM_PLCC_TXNS_12MO_SLS BIGINT,
GROSS_SALES_AMT_6MO_RTN DOUBLE,
DISCOUNT_AMT_6MO_RTN DOUBLE,
ITEM_QTY_6MO_RTN BIGINT,
GROSS_SALES_AMT_12MO_RTN DOUBLE,
DISCOUNT_AMT_12MO_RTN DOUBLE,
ITEM_QTY_12MO_RTN BIGINT,
NUM_TXNS_6MO_RTN BIGINT,
NUM_TXNS_12MO_RTN BIGINT,
SHIP_AMOUNT_6MO_SLS_CP DOUBLE,
GROSS_SALES_AMT_6MO_SLS_CP DOUBLE,
DISCOUNT_AMT_6MO_SLS_CP DOUBLE,
TOT_PRD_CST_AMT_6MO_SLS_CP DOUBLE,
ITEM_QTY_6MO_SLS_CP BIGINT,
SHIP_AMOUNT_12MO_SLS_CP DOUBLE,
GROSS_SALES_AMT_12MO_SLS_CP DOUBLE,
DISCOUNT_AMT_12MO_SLS_CP DOUBLE,
TOT_PRD_CST_AMT_12MO_SLS_CP DOUBLE,
ITEM_QTY_12MO_SLS_CP BIGINT,
NUM_TXNS_6MO_SLS_CP BIGINT,
NUM_TXNS_12MO_SLS_CP BIGINT,
NUM_PLCC_TXNS_6MO_SLS_CP BIGINT,
NUM_PLCC_TXNS_12MO_SLS_CP BIGINT,
GROSS_SALES_AMT_6MO_RTN_CP DOUBLE,
DISCOUNT_AMT_6MO_RTN_CP DOUBLE,
ITEM_QTY_6MO_RTN_CP BIGINT,
GROSS_SALES_AMT_12MO_RTN_CP DOUBLE,
DISCOUNT_AMT_12MO_RTN_CP DOUBLE,
ITEM_QTY_12MO_RTN_CP BIGINT,
NUM_TXNS_6MO_RTN_CP BIGINT,
NUM_TXNS_12MO_RTN_CP BIGINT,
SHIP_AMOUNT_6MO_ONL_SLS DOUBLE,
GROSS_SALES_AMT_6MO_ONL_SLS DOUBLE,
DISCOUNT_AMT_6MO_ONL_SLS DOUBLE,
TOT_PRD_CST_AMT_6MO_ONL_SLS DOUBLE,
ITEM_QTY_6MO_ONL_SLS BIGINT,
SHIP_AMOUNT_12MO_ONL_SLS DOUBLE,
GROSS_SALES_AMT_12MO_ONL_SLS DOUBLE,
DISCOUNT_AMT_12MO_ONL_SLS DOUBLE,
TOT_PRD_CST_AMT_12MO_ONL_SLS DOUBLE,
ITEM_QTY_12MO_ONL_SLS BIGINT,
NUM_TXNS_6MO_ONL_SLS BIGINT,
NUM_TXNS_12MO_ONL_SLS BIGINT,
BASIC_FLAG INT,
SILVER_FLAG INT,
SISTER_FLAG INT,
CARD_STATUS INT,
DAYS_LAST_PUR_CP INT,
DAYS_LAST_PUR_${hiveconf:CURRENT_BRAND} INT,
DAYS_ON_BOOKS_CP INT,
DIV_SHP_${hiveconf:CURRENT_BRAND} BIGINT,
ONSALE_QTY_12MO BIGINT,
ONSALE_QTY_6MO BIGINT,
PROMOTIONS_RECEIVED_CP BIGINT,
PROMOTIONS_RECEIVED_${hiveconf:CURRENT_BRAND} BIGINT,
${hiveconf:CURRENT_BRAND}_CAMPAIGNS_RECEIVED_12MO BIGINT,
${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO BIGINT,
${hiveconf:CURRENT_BRAND}_PROMOTIONS_RESPONDED_12MO BIGINT,
RESPONSE_RATE_12MO DOUBLE,
NUM_TXNS_SLS_PROMO_12MO BIGINT,
GROSS_SALES_SLS_PROMO_12MO DOUBLE,
DISCOUNT_SLS_PROMO_12MO DOUBLE,
NET_SALES_SLS_PROMO_12MO DOUBLE,
EMAILS_CLICKED_${hiveconf:CURRENT_BRAND} BIGINT,
EMAILS_CLICKED_CP BIGINT,
EMAILS_VIEWED_${hiveconf:CURRENT_BRAND} BIGINT,
EMAILS_VIEWED_CP BIGINT,
START_DT STRING,
END_DT STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
LOCATION '/user/tghosh/${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM';



INSERT OVERWRITE TABLE ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED_TXT
SELECT 
T1.CUSTOMER_KEY,
T1.GROSS_SALES_AMT,
T1.DISCOUNT_AMT,
T1.TOT_PRD_CST_AMT,
T1.ITEM_QTY,
T1.NET_SALES_AMT,
T1.NUM_TXNS,
T1.AVG_ORD_SZ,
T1.RESPONDER,
T1.SHIP_AMOUNT_6MO_SLS,
T1.GROSS_SALES_AMT_6MO_SLS,
T1.DISCOUNT_AMT_6MO_SLS,
T1.TOT_PRD_CST_AMT_6MO_SLS,
T1.ITEM_QTY_6MO_SLS,
T1.SHIP_AMOUNT_12MO_SLS,
T1.GROSS_SALES_AMT_12MO_SLS,
T1.DISCOUNT_AMT_12MO_SLS,
T1.TOT_PRD_CST_AMT_12MO_SLS,
T1.ITEM_QTY_12MO_SLS,
T1.NUM_TXNS_6MO_SLS,
T1.NUM_TXNS_12MO_SLS,
T1.NUM_PLCC_TXNS_6MO_SLS,
T1.NUM_PLCC_TXNS_12MO_SLS,
T1.GROSS_SALES_AMT_6MO_RTN,
T1.DISCOUNT_AMT_6MO_RTN,
T1.ITEM_QTY_6MO_RTN,
T1.GROSS_SALES_AMT_12MO_RTN,
T1.DISCOUNT_AMT_12MO_RTN,
T1.ITEM_QTY_12MO_RTN,
T1.NUM_TXNS_6MO_RTN,
T1.NUM_TXNS_12MO_RTN,
T1.SHIP_AMOUNT_6MO_SLS_CP,
T1.GROSS_SALES_AMT_6MO_SLS_CP,
T1.DISCOUNT_AMT_6MO_SLS_CP,
T1.TOT_PRD_CST_AMT_6MO_SLS_CP,
T1.ITEM_QTY_6MO_SLS_CP,
T1.SHIP_AMOUNT_12MO_SLS_CP,
T1.GROSS_SALES_AMT_12MO_SLS_CP,
T1.DISCOUNT_AMT_12MO_SLS_CP,
T1.TOT_PRD_CST_AMT_12MO_SLS_CP,
T1.ITEM_QTY_12MO_SLS_CP,
T1.NUM_TXNS_6MO_SLS_CP,
T1.NUM_TXNS_12MO_SLS_CP,
T1.NUM_PLCC_TXNS_6MO_SLS_CP,
T1.NUM_PLCC_TXNS_12MO_SLS_CP,
T1.GROSS_SALES_AMT_6MO_RTN_CP,
T1.DISCOUNT_AMT_6MO_RTN_CP,
T1.ITEM_QTY_6MO_RTN_CP,
T1.GROSS_SALES_AMT_12MO_RTN_CP,
T1.DISCOUNT_AMT_12MO_RTN_CP,
T1.ITEM_QTY_12MO_RTN_CP,
T1.NUM_TXNS_6MO_RTN_CP,
T1.NUM_TXNS_12MO_RTN_CP,
T1.SHIP_AMOUNT_6MO_ONL_SLS,
T1.GROSS_SALES_AMT_6MO_ONL_SLS,
T1.DISCOUNT_AMT_6MO_ONL_SLS,
T1.TOT_PRD_CST_AMT_6MO_ONL_SLS,
T1.ITEM_QTY_6MO_ONL_SLS,
T1.SHIP_AMOUNT_12MO_ONL_SLS,
T1.GROSS_SALES_AMT_12MO_ONL_SLS,
T1.DISCOUNT_AMT_12MO_ONL_SLS,
T1.TOT_PRD_CST_AMT_12MO_ONL_SLS,
T1.ITEM_QTY_12MO_ONL_SLS,
T1.NUM_TXNS_6MO_ONL_SLS,
T1.NUM_TXNS_12MO_ONL_SLS,
T1.BASIC_FLAG,
T1.SILVER_FLAG,
T1.SISTER_FLAG,
T1.CARD_STATUS,
T1.DAYS_LAST_PUR_CP,
T1.DAYS_LAST_PUR_${hiveconf:CURRENT_BRAND},
T1.DAYS_ON_BOOKS_CP,
T1.DIV_SHP_${hiveconf:CURRENT_BRAND},
T1.ONSALE_QTY_12MO,
T1.ONSALE_QTY_6MO,
T1.PROMOTIONS_RECEIVED_CP,
T1.PROMOTIONS_RECEIVED_${hiveconf:CURRENT_BRAND},
T1.${hiveconf:CURRENT_BRAND}_CAMPAIGNS_RECEIVED_12MO,
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RECEIVED_12MO,
T1.${hiveconf:CURRENT_BRAND}_PROMOTIONS_RESPONDED_12MO,
T1.RESPONSE_RATE_12MO,
T1.NUM_TXNS_SLS_PROMO_12MO,
T1.GROSS_SALES_SLS_PROMO_12MO,
T1.DISCOUNT_SLS_PROMO_12MO,
T1.NET_SALES_SLS_PROMO_12MO,
T1.EMAILS_CLICKED_${hiveconf:CURRENT_BRAND},
T1.EMAILS_CLICKED_CP,
T1.EMAILS_VIEWED_${hiveconf:CURRENT_BRAND},
T1.EMAILS_VIEWED_CP,
T1.START_DT,
T1.END_DT
FROM ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED T1;




DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EM;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_1; 

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_2;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_3;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_4;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_AGG_5;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_CUST_CARD_STATUS;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_LAST_PUR;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DAYS_ON_BOOKS_CP;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DIV_SHP;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_ON_SALE_PUR;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_PROMO_RECEIVED;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_PROMOTIONS_P365;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILCLICKS;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_EMAILVIEWS;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_COMBINED;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_DATERANGE;

DROP TABLE IF EXISTS ${hiveconf:CURRENT_BRAND}_EM_${hiveconf:CAMPAIGN_VERSION}.${hiveconf:CURRENT_BRAND}_${hiveconf:CAMPAIGN_VERSION}_TRANSACTIONS;



