LIBNAME TITANLIB "Z:\TANUMOY\WORKSPACE\DATA\TITAN";

OPTIONS MACROGEN SYMBOLGEN MPRINT MLOGIC;

PROC SQL;
 CREATE TABLE TITANLIB.CUST_SAMP_SUMM_BROL AS SELECT DISTINCT TITAN_CUST_ID, CUST_TYPE, RTN_GRP,
 			  SUM(GRS_DMD_AMT) AS GRS_DMD_AMT, SUM(NET_DMD_AMT) AS NET_DMD_AMT,
			  SUM(TOT_REV_AMT) AS TOT_REV_AMT, SUM(TOT_MGN_AMT) AS TOT_MGN_AMT,
			  SUM(VARIABL_MGN_AMT) AS VAR_MGN_AMT, SUM(SHP_MERCH_UN_CNT) AS SHP_UN_CNT,
			  SUM(NET_SLS_AMT) AS NET_SLS_AMT, COUNT(DISTINCT OMS_ORD_KEY) AS NUM_TXNS,
			  PUT(MIN(BR_FST_PRCH_DT), DATE9.) AS BR_FST_PRCH_DT, 
			  PUT(MIN(GID_FST_PRCH_DT), DATE9.) AS GID_FST_PRCH_DT,
			  PUT(MIN(ORDER_DATE), DATE9.) AS FST_ORD_DT, 
			  PUT(MAX(ORDER_DATE), DATE9.) AS LAST_ORD_DT
        FROM TITANLIB.CUST_TXN_SAMP_BROL WHERE SHP_MERCH_UN_CNT>0
	    GROUP BY TITAN_CUST_ID, CUST_TYPE ORDER BY TITAN_CUST_ID, CUST_TYPE;
QUIT;

DATA TITANLIB.CUST_SAMP_SUMM_BROL;
 SET TITANLIB.CUST_SAMP_SUMM_BROL;
 AVG_GRS_DMD_TXN=GRS_DMD_AMT/NUM_TXNS;
 AVG_NET_DMD_TXN=NET_DMD_AMT/NUM_TXNS;
 AVG_TOT_REV_TXN=TOT_REV_AMT/NUM_TXNS;
 AVG_VAR_MGN_TXN=VAR_MGN_AMT/NUM_TXNS;
 AVG_SHP_UNT_TXN=SHP_UN_CNT/NUM_TXNS;
 AVG_GRS_DMD_UNT=GRS_DMD_AMT/SHP_UN_CNT;
 AVG_NET_DMD_UNT=NET_DMD_AMT/SHP_UN_CNT;
 AVG_TOT_REV_UNT=TOT_REV_AMT/SHP_UN_CNT;
 AVG_VAR_MGN_UNT=VAR_MGN_AMT/SHP_UN_CNT;
 DAYS_BR_CUST=INPUT(LAST_ORD_DT,DATE9.)-INPUT(BR_FST_PRCH_DT,DATE9.);
 DAYS_GID_CUST=INPUT(LAST_ORD_DT,DATE9.)-INPUT(GID_FST_PRCH_DT,DATE9.);
 INIT_RTL_PCT=NET_DMD_AMT/GRS_DMD_AMT*100;
RUN;

PROC SORT DATA=TITANLIB.CUST_SAMP_SUMM_BROL;
 BY CUST_TYPE;
RUN;

PROC LOGISTIC DATA=TITANLIB.CUST_SAMP_SUMM_BROL OUTEST=TITANLIB.BROL_MODEL;
 MODEL RTN_GRP(EVENT='1')= AVG_SHP_UNT_TXN INIT_RTL_PCT DAYS_BR_CUST DAYS_GID_CUST
                           AVG_GRS_DMD_TXN AVG_NET_DMD_TXN AVG_TOT_REV_TXN AVG_VAR_MGN_TXN
						   AVG_GRS_DMD_UNT AVG_NET_DMD_UNT AVG_TOT_REV_UNT AVG_VAR_MGN_UNT/
                           CTABLE LACKFIT SELECTION=STEPWISE;
 OUTPUT OUT=TITANLIB.BROL_PRED P=PHAT LOWER=LCL UPPER=UCL PREDPROBS=(INDIVIDUAL CROSSVALIDATE);
QUIT;

PROC DISCRIM DATA=TITANLIB.CUST_SAMP_SUMM_BROL ANOVA LISTERR METHOD=NORMAL CROSSLIST CROSSVALIDATE;
 CLASS RTN_GRP;
 WHERE CUST_TYPE="ACTV";
 VAR AVG_ORD_SZ_UN INIT_RTL_PCT DAYS_BR_CUST DAYS_GID_CUST
     AVG_GRS_DMD AVG_NET_DMD AVG_TOT_REV AVG_VAR_MGN;
 ID TITAN_CUST_ID;
 PRIORS EQUAL;
RUN;
