LIBNAME TA4U1R9 ORACLE USER=TA4U1R9 PW="T$numoy009$!" PATH=SAS10P1 PRESERVE_TAB_NAMES=YES SCHEMA=TA4U1R9;

LIBNAME CORESAS ORACLE USER=TA4U1R9 PW="T$numoy009$!" PATH=SAS10P1 PRESERVE_TAB_NAMES=YES SCHEMA=CORESAS;

LIBNAME DATALIB "\\10.8.8.51\LV0\TANUMOY\DATASETS\MODEL REPLICATION";

OPTIONS MACROGEN SYMBOLGEN MLOGIC MPRINT;



DATA DATALIB.BR_ALLCAMPAIGNS_RESPONDERS;
 SET DATALIB.BR_ALLCAMPAIGNS_BALANCED_MOD;
 WHERE RESPONDER=1;
RUN;



PROC UNIVARIATE DATA=DATALIB.BR_ALLCAMPAIGNS_RESPONDERS;
VAR NET_SALES_AMT;
OUTPUT OUT=DATALIB.BR_NET_SLS_PROMO_PCTL
	   PCTLPRE = NET_SALES_AMT_
	   PCTLPTS= 0.5 50 99.5;
RUN;

DATA BR_ALLCAMPAIGNS_RESPONDERS_1;
 KEEP NET_SALES_AMT 
	  AVG_ORD_SZ_12MO_CP 
	  AVG_ORD_SZ_12MO 
 	  CARD_STATUS
	  ONSALE_QTY_12MO 
	  NET_SALES_AMT_12MO_RTN 
	  NET_SALES_AMT_12MO_SLS
	  AVG_UNT_RTL_CP 
	  AVG_UNT_RTL 
	  DISCOUNT_PCT_12MO 
	  YEARS_ON_BOOKS 
	  UNITS_PER_TXN_12MO_SLS 
	  NUM_TXNS_12MO_SLS  
	  NUM_TXNS_12MO_RTN
      DIV_SHP_BR 
	  BR_PROMOTIONS_RECEIVED_12MO 
	  ONSALE_QTY_6MO
	  TREATMENT_GROUP 
	  CUSTOMER_KEY 
	  RESPONDER 
	  TRAINING 
	  CAMPAIGN 
	  TESTING  
	  OFFSET 
	  WT 
	  TREATMENT_CODE 
	  LENGTH_PROMO 
	  DAYS_LAST_PUR_BR 
	  DAYS_LAST_PUR_CP 
	  PLCC_TXN_PCT 
	  NUM_PLCC_TXNS_12MO_SLS 
	  RESPONSE_RATE_12MO 
	  BASIC_FLAG 
	  SILVER_FLAG 
	  SISTER_FLAG;
SET DATALIB.BR_ALLCAMPAIGNS_RESPONDERS; 
RUN;


DATA DATALIB.BR_ALLCAMPAIGNS_COMBINED_PCTL;
SET DATALIB.BR_ALLCAMPAIGNS_COMBINED_PCTL;

CALL SYMPUT ("AVG_ORD_SZ_12MO_LC", AVG_ORD_SZ_12MO_0_5);
CALL SYMPUT ("AVG_ORD_SZ_12MO_50", AVG_ORD_SZ_12MO_50);
CALL SYMPUT ("AVG_ORD_SZ_12MO_UC", AVG_ORD_SZ_12MO_99_5);
CALL SYMPUT ("AVG_ORD_SZ_12MO_CP_LC", AVG_ORD_SZ_12MO_CP_0_5);
CALL SYMPUT ("AVG_ORD_SZ_12MO_CP_50", AVG_ORD_SZ_12MO_CP_50);
CALL SYMPUT ("AVG_ORD_SZ_12MO_CP_UC", AVG_ORD_SZ_12MO_CP_99_5);
CALL SYMPUT ("AVG_UNT_RTL_LC", AVG_UNT_RTL_0_5);
CALL SYMPUT ("AVG_UNT_RTL_50", AVG_UNT_RTL_50);
CALL SYMPUT ("AVG_UNT_RTL_UC", AVG_UNT_RTL_99_5);
CALL SYMPUT ("AVG_UNT_RTL_CP_LC", AVG_UNT_RTL_CP_0_5);
CALL SYMPUT ("AVG_UNT_RTL_CP_50", AVG_UNT_RTL_CP_50);
CALL SYMPUT ("AVG_UNT_RTL_CP_UC", AVG_UNT_RTL_CP_99_5);
CALL SYMPUT ("BR_PROMOTIONS_RECEIVED_12MO_LC", BR_PROMOTIONS_RECEIVED_12MO_0_5);
CALL SYMPUT ("BR_PROMOTIONS_RECEIVED_12MO_50", BR_PROMOTIONS_RECEIVED_12MO_50);
CALL SYMPUT ("BR_PROMOTIONS_RECEIVED_12MO_UC", BR_PROMOTIONS_RECEIVED_12MO_99_5);
CALL SYMPUT ("DAYS_LAST_PUR_BR_LC", DAYS_LAST_PUR_BR_0_5);
CALL SYMPUT ("DAYS_LAST_PUR_BR_50", DAYS_LAST_PUR_BR_50);
CALL SYMPUT ("DAYS_LAST_PUR_BR_UC", DAYS_LAST_PUR_BR_99_5);
CALL SYMPUT ("DAYS_LAST_PUR_CP_LC", DAYS_LAST_PUR_CP_0_5);
CALL SYMPUT ("DAYS_LAST_PUR_CP_50", DAYS_LAST_PUR_CP_50);
CALL SYMPUT ("DAYS_LAST_PUR_CP_UC", DAYS_LAST_PUR_CP_99_5);
CALL SYMPUT ("DISCOUNT_PCT_12MO_LC", DISCOUNT_PCT_12MO_0_5);
CALL SYMPUT ("DISCOUNT_PCT_12MO_50", DISCOUNT_PCT_12MO_50);
CALL SYMPUT ("DISCOUNT_PCT_12MO_UC", DISCOUNT_PCT_12MO_99_5);
CALL SYMPUT ("DIV_SHP_BR_LC", DIV_SHP_BR_0_5);
CALL SYMPUT ("DIV_SHP_BR_50", DIV_SHP_BR_50);
CALL SYMPUT ("DIV_SHP_BR_UC", DIV_SHP_BR_99_5);
CALL SYMPUT ("NET_SALES_AMT_12MO_RTN_LC", NET_SALES_AMT_12MO_RTN_0_5);
CALL SYMPUT ("NET_SALES_AMT_12MO_RTN_50", NET_SALES_AMT_12MO_RTN_50);
CALL SYMPUT ("NET_SALES_AMT_12MO_RTN_UC", NET_SALES_AMT_12MO_RTN_99_5);
CALL SYMPUT ("NET_SALES_AMT_12MO_SLS_LC", NET_SALES_AMT_12MO_SLS_0_5);
CALL SYMPUT ("NET_SALES_AMT_12MO_SLS_50", NET_SALES_AMT_12MO_SLS_50);
CALL SYMPUT ("NET_SALES_AMT_12MO_SLS_UC", NET_SALES_AMT_12MO_SLS_99_5);
CALL SYMPUT ("NUM_PLCC_TXNS_12MO_SLS_LC", NUM_PLCC_TXNS_12MO_SLS_0_5);
CALL SYMPUT ("NUM_PLCC_TXNS_12MO_SLS_50", NUM_PLCC_TXNS_12MO_SLS_50);
CALL SYMPUT ("NUM_PLCC_TXNS_12MO_SLS_UC", NUM_PLCC_TXNS_12MO_SLS_99_5);
CALL SYMPUT ("NUM_TXNS_12MO_RTN_LC", NUM_TXNS_12MO_RTN_0_5);
CALL SYMPUT ("NUM_TXNS_12MO_RTN_50", NUM_TXNS_12MO_RTN_50);
CALL SYMPUT ("NUM_TXNS_12MO_RTN_UC", NUM_TXNS_12MO_RTN_99_5);
CALL SYMPUT ("NUM_TXNS_12MO_SLS_LC", NUM_TXNS_12MO_SLS_0_5);
CALL SYMPUT ("NUM_TXNS_12MO_SLS_50", NUM_TXNS_12MO_SLS_50);
CALL SYMPUT ("NUM_TXNS_12MO_SLS_UC", NUM_TXNS_12MO_SLS_99_5);
CALL SYMPUT ("ONSALE_QTY_12MO_LC", ONSALE_QTY_12MO_0_5);
CALL SYMPUT ("ONSALE_QTY_12MO_50", ONSALE_QTY_12MO_50);
CALL SYMPUT ("ONSALE_QTY_12MO_UC", ONSALE_QTY_12MO_99_5);
CALL SYMPUT ("ONSALE_QTY_6MO_LC", ONSALE_QTY_6MO_0_5);
CALL SYMPUT ("ONSALE_QTY_6MO_50", ONSALE_QTY_6MO_50);
CALL SYMPUT ("ONSALE_QTY_6MO_UC", ONSALE_QTY_6MO_99_5);
CALL SYMPUT ("PLCC_TXN_PCT_LC", PLCC_TXN_PCT_0_5);
CALL SYMPUT ("PLCC_TXN_PCT_50", PLCC_TXN_PCT_50);
CALL SYMPUT ("PLCC_TXN_PCT_UC", PLCC_TXN_PCT_99_5);
CALL SYMPUT ("UNITS_PER_TXN_12MO_SLS_LC", UNITS_PER_TXN_12MO_SLS_0_5);
CALL SYMPUT ("UNITS_PER_TXN_12MO_SLS_50", UNITS_PER_TXN_12MO_SLS_50);
CALL SYMPUT ("UNITS_PER_TXN_12MO_SLS_UC", UNITS_PER_TXN_12MO_SLS_99_5);
CALL SYMPUT ("YEARS_ON_BOOKS_LC", YEARS_ON_BOOKS_0_5);
CALL SYMPUT ("YEARS_ON_BOOKS_50", YEARS_ON_BOOKS_50);
CALL SYMPUT ("YEARS_ON_BOOKS_UC", YEARS_ON_BOOKS_99_5);

RUN;


DATA DATALIB.BR_NET_SLS_PROMO_PCTL; 
 SET DATALIB.BR_NET_SLS_PROMO_PCTL;
 CALL SYMPUT ("NET_SALES_AMT_LC", NET_SALES_AMT_0_5);
 CALL SYMPUT ("NET_SALES_AMT_50", NET_SALES_AMT_50);
 CALL SYMPUT ("NET_SALES_AMT_UC", NET_SALES_AMT_99_5);
RUN;


DATA BR_ALLCAMPAIGNS_RESPONDERS_2;
SET BR_ALLCAMPAIGNS_RESPONDERS_1;

IF NET_SALES_AMT_SLS GT &NET_SALES_AMT_SLS_UC THEN NET_SALES_AMT_SLS = &NET_SALES_AMT_SLS_UC;
IF AVG_ORD_SZ_12MO GT &AVG_ORD_SZ_12MO_UC THEN AVG_ORD_SZ_12MO = &AVG_ORD_SZ_12MO_UC;
IF AVG_ORD_SZ_12MO_CP GT &AVG_ORD_SZ_12MO_CP_UC THEN AVG_ORD_SZ_12MO_CP = &AVG_ORD_SZ_12MO_CP_UC;
IF AVG_UNT_RTL GT &AVG_UNT_RTL_UC THEN AVG_UNT_RTL = &AVG_UNT_RTL_UC;
IF AVG_UNT_RTL_CP GT &AVG_UNT_RTL_CP_UC THEN AVG_UNT_RTL_CP = &AVG_UNT_RTL_CP_UC;
IF BR_PROMOTIONS_RECEIVED_12MO GT &BR_PROMOTIONS_RECEIVED_12MO_UC THEN BR_PROMOTIONS_RECEIVED_12MO = &BR_PROMOTIONS_RECEIVED_12MO_UC;
IF DAYS_LAST_PUR_BR GT &DAYS_LAST_PUR_BR_UC THEN DAYS_LAST_PUR_BR = &DAYS_LAST_PUR_BR_UC;
IF DAYS_LAST_PUR_CP GT &DAYS_LAST_PUR_CP_UC THEN DAYS_LAST_PUR_CP = &DAYS_LAST_PUR_CP_UC;
IF DISCOUNT_PCT_12MO GT &DISCOUNT_PCT_12MO_UC THEN DISCOUNT_PCT_12MO = &DISCOUNT_PCT_12MO_UC;
IF DIV_SHP_BR GT &DIV_SHP_BR_UC THEN DIV_SHP_BR = &DIV_SHP_BR_UC;
IF NET_SALES_AMT_12MO_RTN GT &NET_SALES_AMT_12MO_RTN_UC THEN NET_SALES_AMT_12MO_RTN = &NET_SALES_AMT_12MO_RTN_UC;
IF NET_SALES_AMT_12MO_SLS GT &NET_SALES_AMT_12MO_SLS_UC THEN NET_SALES_AMT_12MO_SLS = &NET_SALES_AMT_12MO_SLS_UC;
IF NUM_PLCC_TXNS_12MO_SLS GT &NUM_PLCC_TXNS_12MO_SLS_UC THEN NUM_PLCC_TXNS_12MO_SLS = &NUM_PLCC_TXNS_12MO_SLS_UC;
IF NUM_TXNS_12MO_RTN GT &NUM_TXNS_12MO_RTN_UC THEN NUM_TXNS_12MO_RTN = &NUM_TXNS_12MO_RTN_UC;
IF NUM_TXNS_12MO_SLS GT &NUM_TXNS_12MO_SLS_UC THEN NUM_TXNS_12MO_SLS = &NUM_TXNS_12MO_SLS_UC;
IF ONSALE_QTY_12MO GT &ONSALE_QTY_12MO_UC THEN ONSALE_QTY_12MO = &ONSALE_QTY_12MO_UC;
IF ONSALE_QTY_6MO GT &ONSALE_QTY_6MO_UC THEN ONSALE_QTY_6MO = &ONSALE_QTY_6MO_UC;
IF PLCC_TXN_PCT GT &PLCC_TXN_PCT_UC THEN PLCC_TXN_PCT = &PLCC_TXN_PCT_UC;
IF UNITS_PER_TXN_12MO_SLS GT &UNITS_PER_TXN_12MO_SLS_UC THEN UNITS_PER_TXN_12MO_SLS = &UNITS_PER_TXN_12MO_SLS_UC;
IF YEARS_ON_BOOKS GT &YEARS_ON_BOOKS_UC THEN YEARS_ON_BOOKS = &YEARS_ON_BOOKS_UC;

IF NET_SALES_AMT_SLS LT &NET_SALES_AMT_SLS_LC THEN NET_SALES_AMT_SLS = &NET_SALES_AMT_SLS_LC;
IF AVG_ORD_SZ_12MO LT &AVG_ORD_SZ_12MO_LC THEN AVG_ORD_SZ_12MO = &AVG_ORD_SZ_12MO_LC;
IF AVG_ORD_SZ_12MO_CP LT &AVG_ORD_SZ_12MO_CP_LC THEN AVG_ORD_SZ_12MO_CP = &AVG_ORD_SZ_12MO_CP_LC;
IF AVG_UNT_RTL LT &AVG_UNT_RTL_LC THEN AVG_UNT_RTL = &AVG_UNT_RTL_LC;
IF AVG_UNT_RTL_CP LT &AVG_UNT_RTL_CP_LC THEN AVG_UNT_RTL_CP = &AVG_UNT_RTL_CP_LC;
IF BR_PROMOTIONS_RECEIVED_12MO LT &BR_PROMOTIONS_RECEIVED_12MO_LC THEN BR_PROMOTIONS_RECEIVED_12MO = &BR_PROMOTIONS_RECEIVED_12MO_LC;
IF DAYS_LAST_PUR_BR LT &DAYS_LAST_PUR_BR_LC THEN DAYS_LAST_PUR_BR = &DAYS_LAST_PUR_BR_LC;
IF DAYS_LAST_PUR_CP LT &DAYS_LAST_PUR_CP_LC THEN DAYS_LAST_PUR_CP = &DAYS_LAST_PUR_CP_LC;
IF DISCOUNT_PCT_12MO LT &DISCOUNT_PCT_12MO_LC THEN DISCOUNT_PCT_12MO = &DISCOUNT_PCT_12MO_LC;
IF DIV_SHP_BR LT &DIV_SHP_BR_LC THEN DIV_SHP_BR = &DIV_SHP_BR_LC;
IF NET_SALES_AMT_12MO_RTN LT &NET_SALES_AMT_12MO_RTN_LC THEN NET_SALES_AMT_12MO_RTN = &NET_SALES_AMT_12MO_RTN_LC;
IF NET_SALES_AMT_12MO_SLS LT &NET_SALES_AMT_12MO_SLS_LC THEN NET_SALES_AMT_12MO_SLS = &NET_SALES_AMT_12MO_SLS_LC;
IF NUM_PLCC_TXNS_12MO_SLS LT &NUM_PLCC_TXNS_12MO_SLS_LC THEN NUM_PLCC_TXNS_12MO_SLS = &NUM_PLCC_TXNS_12MO_SLS_LC;
IF NUM_TXNS_12MO_RTN LT &NUM_TXNS_12MO_RTN_LC THEN NUM_TXNS_12MO_RTN = &NUM_TXNS_12MO_RTN_LC;
IF NUM_TXNS_12MO_SLS LT &NUM_TXNS_12MO_SLS_LC THEN NUM_TXNS_12MO_SLS = &NUM_TXNS_12MO_SLS_LC;
IF ONSALE_QTY_12MO LT &ONSALE_QTY_12MO_LC THEN ONSALE_QTY_12MO = &ONSALE_QTY_12MO_LC;
IF ONSALE_QTY_6MO LT &ONSALE_QTY_6MO_LC THEN ONSALE_QTY_6MO = &ONSALE_QTY_6MO_LC;
IF PLCC_TXN_PCT LT &PLCC_TXN_PCT_LC THEN PLCC_TXN_PCT = &PLCC_TXN_PCT_LC;
IF UNITS_PER_TXN_12MO_SLS LT &UNITS_PER_TXN_12MO_SLS_LC THEN UNITS_PER_TXN_12MO_SLS = &UNITS_PER_TXN_12MO_SLS_LC;
IF YEARS_ON_BOOKS LT &YEARS_ON_BOOKS_LC THEN YEARS_ON_BOOKS = &YEARS_ON_BOOKS_LC;

RUN;

DATA BR_ALLCAMPAIGNS_RESPONDERS_3;
SET BR_ALLCAMPAIGNS_RESPONDERS_2;
AVG_ORD_SZ_12MO = (AVG_ORD_SZ_12MO - &AVG_ORD_SZ_12MO_LC) / (&AVG_ORD_SZ_12MO_UC - &AVG_ORD_SZ_12MO_LC);
AVG_ORD_SZ_12MO_CP = (AVG_ORD_SZ_12MO_CP - &AVG_ORD_SZ_12MO_CP_LC) / (&AVG_ORD_SZ_12MO_CP_UC - &AVG_ORD_SZ_12MO_CP_LC);
AVG_UNT_RTL = (AVG_UNT_RTL - &AVG_UNT_RTL_LC) / (&AVG_UNT_RTL_UC - &AVG_UNT_RTL_LC);
AVG_UNT_RTL_CP = (AVG_UNT_RTL_CP - &AVG_UNT_RTL_CP_LC) / (&AVG_UNT_RTL_CP_UC - &AVG_UNT_RTL_CP_LC);
BR_PROMOTIONS_RECEIVED_12MO = (BR_PROMOTIONS_RECEIVED_12MO - &BR_PROMOTIONS_RECEIVED_12MO_LC) / (&BR_PROMOTIONS_RECEIVED_12MO_UC - &BR_PROMOTIONS_RECEIVED_12MO_LC);
DAYS_LAST_PUR_BR = (DAYS_LAST_PUR_BR - &DAYS_LAST_PUR_BR_LC) / (&DAYS_LAST_PUR_BR_UC - &DAYS_LAST_PUR_BR_LC);
DAYS_LAST_PUR_CP = (DAYS_LAST_PUR_CP - &DAYS_LAST_PUR_CP_LC) / (&DAYS_LAST_PUR_CP_UC - &DAYS_LAST_PUR_CP_LC);
DISCOUNT_PCT_12MO = (DISCOUNT_PCT_12MO - &DISCOUNT_PCT_12MO_LC) / (&DISCOUNT_PCT_12MO_UC - &DISCOUNT_PCT_12MO_LC);
DIV_SHP_BR = (DIV_SHP_BR - &DIV_SHP_BR_LC) / (&DIV_SHP_BR_UC - &DIV_SHP_BR_LC);
NET_SALES_AMT_12MO_RTN = (NET_SALES_AMT_12MO_RTN - &NET_SALES_AMT_12MO_RTN_LC) / (&NET_SALES_AMT_12MO_RTN_UC - &NET_SALES_AMT_12MO_RTN_LC);
NET_SALES_AMT_12MO_SLS = (NET_SALES_AMT_12MO_SLS - &NET_SALES_AMT_12MO_SLS_LC) / (&NET_SALES_AMT_12MO_SLS_UC - &NET_SALES_AMT_12MO_SLS_LC);
NUM_PLCC_TXNS_12MO_SLS = (NUM_PLCC_TXNS_12MO_SLS - &NUM_PLCC_TXNS_12MO_SLS_LC) / (&NUM_PLCC_TXNS_12MO_SLS_UC - &NUM_PLCC_TXNS_12MO_SLS_LC);
NUM_TXNS_12MO_RTN = (NUM_TXNS_12MO_RTN - &NUM_TXNS_12MO_RTN_LC) / (&NUM_TXNS_12MO_RTN_UC - &NUM_TXNS_12MO_RTN_LC);
NUM_TXNS_12MO_SLS = (NUM_TXNS_12MO_SLS - &NUM_TXNS_12MO_SLS_LC) / (&NUM_TXNS_12MO_SLS_UC - &NUM_TXNS_12MO_SLS_LC);
ONSALE_QTY_12MO = (ONSALE_QTY_12MO - &ONSALE_QTY_12MO_LC) / (&ONSALE_QTY_12MO_UC - &ONSALE_QTY_12MO_LC);
ONSALE_QTY_6MO = (ONSALE_QTY_6MO - &ONSALE_QTY_6MO_LC) / (&ONSALE_QTY_6MO_UC - &ONSALE_QTY_6MO_LC);
PLCC_TXN_PCT = (PLCC_TXN_PCT - &PLCC_TXN_PCT_LC) / (&PLCC_TXN_PCT_UC - &PLCC_TXN_PCT_LC);
UNITS_PER_TXN_12MO_SLS = (UNITS_PER_TXN_12MO_SLS - &UNITS_PER_TXN_12MO_SLS_LC) / (&UNITS_PER_TXN_12MO_SLS_UC - &UNITS_PER_TXN_12MO_SLS_LC);
YEARS_ON_BOOKS = (YEARS_ON_BOOKS - &YEARS_ON_BOOKS_LC) / (&YEARS_ON_BOOKS_UC - &YEARS_ON_BOOKS_LC);
RUN;

DATA DATALIB.BR_ALLCAMPAIGNS_RESPONDERS_MOD;
 SET BR_ALLCAMPAIGNS_RESPONDERS_3;
RUN;

PROC EXPORT DATA=DATALIB.BR_ALLCAMPAIGNS_RESPONDERS_MOD
			OUTFILE="Z:\TANUMOY\DATASETS\MODEL REPLICATION\BR_ALLCAMPAIGNS_RESPONDERS_MOD.TXT"
            DBMS=DLM REPLACE;
     DELIMITER="|";
RUN;

PROC REG DATA=BR_ALLCAMPAIGNS_RESPONDERS_3 OUTEST=DATALIB.BR_ALLCAMPAIGNS_REVEST;
 MODEL NET_SALES_AMT =  ONSALE_QTY_12MO NET_SALES_AMT_12MO_SLS RESPONSE_RATE_12MO
						AVG_UNT_RTL DISCOUNT_PCT_12MO YEARS_ON_BOOKS PLCC_TXN_PCT 
						AVG_ORD_SZ_12MO 
						/VIF;
 WHERE TRAINING=1;
 OUTPUT OUT=BR_ALLCAMPAIGNS_RESPONDERS_3_P 
 RSTUDENT=RSTUDENT H=LEVERAGE COOKD=COOKD DFFITS=DFFITS P=YHAT;;
RUN;
QUIT;

OPTIONS NOPRINT;

PROC HPMIXED DATA=BR_ALLCAMPAIGNS_RESPONDERS_3 METHOD=REML;
 CLASS CARD_STATUS;
 MODEL NET_SALES_AMT =  ONSALE_QTY_12MO NET_SALES_AMT_12MO_SLS RESPONSE_RATE_12MO
						AVG_UNT_RTL DISCOUNT_PCT_12MO YEARS_ON_BOOKS PLCC_TXN_PCT 
						UNITS_PER_TXN_12MO_SLS DIV_SHP_BR / SOLUTION;
 RANDOM INTERCEPT NET_SALES_AMT_12MO_SLS AVG_UNT_RTL RESPONSE_RATE_12MO/SUB=CARD_STATUS;
RUN;
