LIBNAME TA4U1R9 ORACLE USER=TA4U1R9 PW="T$numoy009$!" PATH=SAS10P1 PRESERVE_TAB_NAMES=YES SCHEMA=TA4U1R9;

LIBNAME CORESAS ORACLE USER=TA4U1R9 PW="T$numoy009$!" PATH=SAS10P1 PRESERVE_TAB_NAMES=YES SCHEMA=CORESAS;

LIBNAME DATALIB "\\10.8.8.51\LV0\TANUMOY\DATASETS\MODEL REPLICATION";

OPTIONS MACROGEN SYMBOLGEN MLOGIC MPRINT;

DATA DATALIB.GP_ALLCAMPAIGNS_RESPONDERS;
 SET DATALIB.GP_ALLCAMPAIGNS_BALANCED;
 WHERE RESPONDER=1;
RUN;

PROC UNIVARIATE DATA=DATALIB.GP_ALLCAMPAIGNS_RESPONDERS;
VAR NET_SALES_AMT;
OUTPUT OUT=DATALIB.GP_NET_SLS_PROMO_PCTL
	   PCTLPRE = NET_SALES_AMT_
	   PCTLPTS= 0.5 50 99.5;
RUN;

DATA GP_ALLCAMPAIGNS_RESPONDERS_1;
KEEP NET_SALES_AMT AVG_ORD_SZ_12MO_CP ONSALE_QTY_12MO AVG_UNT_RTL_CP
	 UNITS_PER_TXN_12MO_SLS DIV_SHP_GP TREATMENT_GROUP RESPONDER
	 ONSALE_QTY_6MO DAYS_LAST_PUR_GP AVG_ORD_SZ_12MO END_DT START_DT
	 NET_SALES_AMT_12MO_RTN AVG_UNT_RTL NUM_TXNS_12MO_SLS
	 CUSTOMER_KEY RESPONDER TREATMENT_CODE DAYS_LAST_PUR_CP
	 NET_SALES_AMT_12MO_SLS DISCOUNT_PCT_12MO NUM_TXNS_12MO_RTN
	 TRAINING CAMPAIGN PLCC_TXN_PCT YEARS_ON_BOOKS OFFSET LENGTH_PROMO
	 TESTING NUM_PLCC_TXNS_12MO_SLS WT GP_PROMOTIONS_RECEIVED_12MO;
SET DATALIB.GP_ALLCAMPAIGNS_RESPONDERS; 
RUN;

DATA DATALIB.GP_ALLCAMPAIGNS_COMBINED_PCTL;
SET DATALIB.GP_ALLCAMPAIGNS_COMBINED_PCTL;
 
 CALL SYMPUT ("AVG_ORD_SZ_12MO_CP_LC", AVG_ORD_SZ_12MO_CP_0_5);
 CALL SYMPUT ("AVG_ORD_SZ_12MO_CP_50", AVG_ORD_SZ_12MO_CP_50);
 CALL SYMPUT ("AVG_ORD_SZ_12MO_CP_UC", AVG_ORD_SZ_12MO_CP_99_5);
 CALL SYMPUT ("AVG_ORD_SZ_12MO_LC", AVG_ORD_SZ_12MO_0_5);
 CALL SYMPUT ("AVG_ORD_SZ_12MO_50", AVG_ORD_SZ_12MO_50);
 CALL SYMPUT ("AVG_ORD_SZ_12MO_UC", AVG_ORD_SZ_12MO_99_5);
 CALL SYMPUT ("ONSALE_QTY_12MO_LC", ONSALE_QTY_12MO_0_5);
 CALL SYMPUT ("ONSALE_QTY_12MO_50", ONSALE_QTY_12MO_50);
 CALL SYMPUT ("ONSALE_QTY_12MO_UC", ONSALE_QTY_12MO_99_5);
 CALL SYMPUT ("NET_SALES_AMT_12MO_RTN_LC", NET_SALES_AMT_12MO_RTN_0_5);
 CALL SYMPUT ("NET_SALES_AMT_12MO_RTN_50", NET_SALES_AMT_12MO_RTN_50);
 CALL SYMPUT ("NET_SALES_AMT_12MO_RTN_UC", NET_SALES_AMT_12MO_RTN_99_5);
 CALL SYMPUT ("NET_SALES_AMT_12MO_SLS_LC", NET_SALES_AMT_12MO_SLS_0_5);
 CALL SYMPUT ("NET_SALES_AMT_12MO_SLS_50", NET_SALES_AMT_12MO_SLS_50);
 CALL SYMPUT ("NET_SALES_AMT_12MO_SLS_UC", NET_SALES_AMT_12MO_SLS_99_5);
 CALL SYMPUT ("AVG_UNT_RTL_CP_LC", AVG_UNT_RTL_CP_0_5);
 CALL SYMPUT ("AVG_UNT_RTL_CP_50", AVG_UNT_RTL_CP_50);
 CALL SYMPUT ("AVG_UNT_RTL_CP_UC", AVG_UNT_RTL_CP_99_5);
 CALL SYMPUT ("AVG_UNT_RTL_LC", AVG_UNT_RTL_0_5);
 CALL SYMPUT ("AVG_UNT_RTL_50", AVG_UNT_RTL_50);
 CALL SYMPUT ("AVG_UNT_RTL_UC", AVG_UNT_RTL_99_5);
 CALL SYMPUT ("DISCOUNT_PCT_12MO_LC", DISCOUNT_PCT_12MO_0_5);
 CALL SYMPUT ("DISCOUNT_PCT_12MO_50", DISCOUNT_PCT_12MO_50);
 CALL SYMPUT ("DISCOUNT_PCT_12MO_UC", DISCOUNT_PCT_12MO_99_5);
 CALL SYMPUT ("YEARS_ON_BOOKS_LC", YEARS_ON_BOOKS_0_5);
 CALL SYMPUT ("YEARS_ON_BOOKS_50", YEARS_ON_BOOKS_50);
 CALL SYMPUT ("YEARS_ON_BOOKS_UC", YEARS_ON_BOOKS_99_5);
 CALL SYMPUT ("UNITS_PER_TXN_12MO_SLS_LC", UNITS_PER_TXN_12MO_SLS_0_5);
 CALL SYMPUT ("UNITS_PER_TXN_12MO_SLS_50", UNITS_PER_TXN_12MO_SLS_50);
 CALL SYMPUT ("UNITS_PER_TXN_12MO_SLS_UC", UNITS_PER_TXN_12MO_SLS_99_5);
 CALL SYMPUT ("NUM_TXNS_12MO_SLS_LC", NUM_TXNS_12MO_SLS_0_5);
 CALL SYMPUT ("NUM_TXNS_12MO_SLS_50", NUM_TXNS_12MO_SLS_50);
 CALL SYMPUT ("NUM_TXNS_12MO_SLS_UC", NUM_TXNS_12MO_SLS_99_5); 
 CALL SYMPUT ("NUM_TXNS_12MO_RTN_LC", NUM_TXNS_12MO_RTN_0_5); 
 CALL SYMPUT ("NUM_TXNS_12MO_RTN_50", NUM_TXNS_12MO_RTN_50);
 CALL SYMPUT ("NUM_TXNS_12MO_RTN_UC", NUM_TXNS_12MO_RTN_99_5);
 CALL SYMPUT ("DIV_SHP_GP_LC", DIV_SHP_GP_0_5);
 CALL SYMPUT ("DIV_SHP_GP_50", DIV_SHP_GP_50);
 CALL SYMPUT ("DIV_SHP_GP_UC", DIV_SHP_GP_99_5);
 CALL SYMPUT ("GP_PROMOTIONS_RECEIVED_12MO_LC", GP_PROMOTIONS_RECEIVED_12MO_0_5);
 CALL SYMPUT ("GP_PROMOTIONS_RECEIVED_12MO_50", GP_PROMOTIONS_RECEIVED_12MO_50);
 CALL SYMPUT ("GP_PROMOTIONS_RECEIVED_12MO_UC", GP_PROMOTIONS_RECEIVED_12MO_99_5);
 CALL SYMPUT ("ONSALE_QTY_6MO_LC", ONSALE_QTY_6MO_0_5);
 CALL SYMPUT ("ONSALE_QTY_6MO_50", ONSALE_QTY_6MO_50);
 CALL SYMPUT ("ONSALE_QTY_6MO_UC", ONSALE_QTY_6MO_99_5); 
 CALL SYMPUT ("DAYS_LAST_PUR_GP_LC", DAYS_LAST_PUR_GP_0_5);
 CALL SYMPUT ("DAYS_LAST_PUR_GP_50", DAYS_LAST_PUR_GP_50);
 CALL SYMPUT ("DAYS_LAST_PUR_GP_UC", DAYS_LAST_PUR_GP_99_5);
 CALL SYMPUT ("DAYS_LAST_PUR_CP_LC", DAYS_LAST_PUR_CP_0_5);
 CALL SYMPUT ("DAYS_LAST_PUR_CP_50", DAYS_LAST_PUR_CP_50);
 CALL SYMPUT ("DAYS_LAST_PUR_CP_UC", DAYS_LAST_PUR_CP_99_5); 
 CALL SYMPUT ("PLCC_TXN_PCT_LC", PLCC_TXN_PCT_0_5);
 CALL SYMPUT ("PLCC_TXN_PCT_50", PLCC_TXN_PCT_50);
 CALL SYMPUT ("PLCC_TXN_PCT_UC", PLCC_TXN_PCT_99_5); 
 CALL SYMPUT ("NUM_PLCC_TXNS_12MO_SLS_LC", NUM_PLCC_TXNS_12MO_SLS_0_5);
 CALL SYMPUT ("NUM_PLCC_TXNS_12MO_SLS_50", NUM_PLCC_TXNS_12MO_SLS_50);
 CALL SYMPUT ("NUM_PLCC_TXNS_12MO_SLS_UC", NUM_PLCC_TXNS_12MO_SLS_99_5); 

RUN;


DATA DATALIB.GP_NET_SLS_PROMO_PCTL; 
 SET DATALIB.GP_NET_SLS_PROMO_PCTL;
 CALL SYMPUT ("NET_SALES_AMT_LC", NET_SALES_AMT_0_5);
 CALL SYMPUT ("NET_SALES_AMT_50", NET_SALES_AMT_50);
 CALL SYMPUT ("NET_SALES_AMT_UC", NET_SALES_AMT_99_5);
RUN;


DATA GP_ALLCAMPAIGNS_RESPONDERS_2;
SET GP_ALLCAMPAIGNS_RESPONDERS_1;

IF NET_SALES_AMT > &NET_SALES_AMT_UC THEN NET_SALES_AMT = &NET_SALES_AMT_UC;
IF AVG_ORD_SZ_12MO_CP > &AVG_ORD_SZ_12MO_CP_UC THEN AVG_ORD_SZ_12MO_CP = &AVG_ORD_SZ_12MO_CP_UC;
IF AVG_ORD_SZ_12MO > &AVG_ORD_SZ_12MO_UC THEN AVG_ORD_SZ_12MO = &AVG_ORD_SZ_12MO_UC;
IF ONSALE_QTY_12MO > &ONSALE_QTY_12MO_UC THEN ONSALE_QTY_12MO = &ONSALE_QTY_12MO_UC;
IF NET_SALES_AMT_12MO_RTN > &NET_SALES_AMT_12MO_RTN_UC THEN NET_SALES_AMT_12MO_RTN = &NET_SALES_AMT_12MO_RTN_UC;
IF NET_SALES_AMT_12MO_SLS > &NET_SALES_AMT_12MO_SLS_UC THEN NET_SALES_AMT_12MO_SLS = &NET_SALES_AMT_12MO_SLS_UC;
IF AVG_UNT_RTL_CP > &AVG_UNT_RTL_CP_UC THEN AVG_UNT_RTL_CP = &AVG_UNT_RTL_CP_UC;
IF AVG_UNT_RTL > &AVG_UNT_RTL_UC THEN AVG_UNT_RTL = &AVG_UNT_RTL_UC;
IF DISCOUNT_PCT_12MO > &DISCOUNT_PCT_12MO_UC THEN DISCOUNT_PCT_12MO = &DISCOUNT_PCT_12MO_UC;
IF YEARS_ON_BOOKS > &YEARS_ON_BOOKS_UC THEN YEARS_ON_BOOKS = &YEARS_ON_BOOKS_UC;
IF UNITS_PER_TXN_12MO_SLS > &UNITS_PER_TXN_12MO_SLS_UC THEN UNITS_PER_TXN_12MO_SLS = &UNITS_PER_TXN_12MO_SLS_UC;
IF NUM_TXNS_12MO_SLS > &NUM_TXNS_12MO_SLS_UC THEN NUM_TXNS_12MO_SLS = &NUM_TXNS_12MO_SLS_UC;
IF NUM_TXNS_12MO_RTN > &NUM_TXNS_12MO_RTN_UC THEN NUM_TXNS_12MO_RTN = &NUM_TXNS_12MO_RTN_UC;
IF DIV_SHP_GP > &DIV_SHP_GP_UC THEN DIV_SHP_GP = &DIV_SHP_GP_UC;
IF GP_PROMOTIONS_RECEIVED_12MO > &GP_PROMOTIONS_RECEIVED_12MO_UC THEN GP_PROMOTIONS_RECEIVED_12MO = &GP_PROMOTIONS_RECEIVED_12MO_UC;
IF ONSALE_QTY_6MO > &ONSALE_QTY_6MO_UC THEN ONSALE_QTY_6MO = &ONSALE_QTY_6MO_UC;
IF DAYS_LAST_PUR_CP > &DAYS_LAST_PUR_CP_UC THEN DAYS_LAST_PUR_CP = &DAYS_LAST_PUR_CP_UC;
IF DAYS_LAST_PUR_GP > &DAYS_LAST_PUR_GP_UC THEN DAYS_LAST_PUR_GP = &DAYS_LAST_PUR_GP_UC;
IF PLCC_TXN_PCT > &PLCC_TXN_PCT_UC THEN PLCC_TXN_PCT = &PLCC_TXN_PCT_UC;
IF NUM_PLCC_TXNS_12MO_SLS > &NUM_PLCC_TXNS_12MO_SLS_UC THEN NUM_PLCC_TXNS_12MO_SLS = &NUM_PLCC_TXNS_12MO_SLS_UC;


IF NET_SALES_AMT > &NET_SALES_AMT_UC THEN NET_SALES_AMT = &NET_SALES_AMT_UC;
IF AVG_ORD_SZ_12MO_CP < &AVG_ORD_SZ_12MO_CP_LC THEN AVG_ORD_SZ_12MO_CP = &AVG_ORD_SZ_12MO_CP_LC;
IF AVG_ORD_SZ_12MO < &AVG_ORD_SZ_12MO_LC THEN AVG_ORD_SZ_12MO = &AVG_ORD_SZ_12MO_LC;
IF ONSALE_QTY_12MO < &ONSALE_QTY_12MO_LC THEN ONSALE_QTY_12MO = &ONSALE_QTY_12MO_LC;
IF NET_SALES_AMT_12MO_RTN < &NET_SALES_AMT_12MO_RTN_LC THEN NET_SALES_AMT_12MO_RTN = &NET_SALES_AMT_12MO_RTN_LC;
IF NET_SALES_AMT_12MO_SLS < &NET_SALES_AMT_12MO_SLS_LC THEN NET_SALES_AMT_12MO_SLS = &NET_SALES_AMT_12MO_SLS_LC;
IF AVG_UNT_RTL_CP < &AVG_UNT_RTL_CP_LC THEN AVG_UNT_RTL_CP = &AVG_UNT_RTL_CP_LC;
IF AVG_UNT_RTL < &AVG_UNT_RTL_LC THEN AVG_UNT_RTL = &AVG_UNT_RTL_LC;
IF DISCOUNT_PCT_12MO < &DISCOUNT_PCT_12MO_LC THEN DISCOUNT_PCT_12MO = &DISCOUNT_PCT_12MO_LC;
IF YEARS_ON_BOOKS < &YEARS_ON_BOOKS_LC THEN YEARS_ON_BOOKS = &YEARS_ON_BOOKS_LC;
IF UNITS_PER_TXN_12MO_SLS < &UNITS_PER_TXN_12MO_SLS_LC THEN UNITS_PER_TXN_12MO_SLS = &UNITS_PER_TXN_12MO_SLS_LC;
IF NUM_TXNS_12MO_SLS < &NUM_TXNS_12MO_SLS_LC THEN NUM_TXNS_12MO_SLS = &NUM_TXNS_12MO_SLS_LC;
IF NUM_TXNS_12MO_RTN < &NUM_TXNS_12MO_RTN_LC THEN NUM_TXNS_12MO_RTN = &NUM_TXNS_12MO_RTN_LC;
IF DIV_SHP_GP < &DIV_SHP_GP_LC THEN DIV_SHP_GP = &DIV_SHP_GP_LC;
IF GP_PROMOTIONS_RECEIVED_12MO < &GP_PROMOTIONS_RECEIVED_12MO_LC THEN GP_PROMOTIONS_RECEIVED_12MO = &GP_PROMOTIONS_RECEIVED_12MO_LC;
IF ONSALE_QTY_6MO < &ONSALE_QTY_6MO_LC THEN ONSALE_QTY_6MO = &ONSALE_QTY_6MO_LC;
IF DAYS_LAST_PUR_CP < &DAYS_LAST_PUR_CP_LC THEN DAYS_LAST_PUR_CP = &DAYS_LAST_PUR_CP_LC;
IF DAYS_LAST_PUR_GP < &DAYS_LAST_PUR_GP_LC THEN DAYS_LAST_PUR_GP = &DAYS_LAST_PUR_GP_LC;
IF PLCC_TXN_PCT < &PLCC_TXN_PCT_LC THEN PLCC_TXN_PCT = &PLCC_TXN_PCT_LC;
IF NUM_PLCC_TXNS_12MO_SLS < &NUM_PLCC_TXNS_12MO_SLS_LC THEN NUM_PLCC_TXNS_12MO_SLS = &NUM_PLCC_TXNS_12MO_SLS_LC;
RUN;

DATA GP_ALLCAMPAIGNS_RESPONDERS_3;
SET GP_ALLCAMPAIGNS_RESPONDERS_2;

AVG_ORD_SZ_12MO_CP = (AVG_ORD_SZ_12MO_CP - &AVG_ORD_SZ_12MO_CP_LC) / (&AVG_ORD_SZ_12MO_CP_UC - &AVG_ORD_SZ_12MO_CP_LC);
AVG_ORD_SZ_12MO = (AVG_ORD_SZ_12MO - &AVG_ORD_SZ_12MO_LC) / (&AVG_ORD_SZ_12MO_UC - &AVG_ORD_SZ_12MO_LC);
ONSALE_QTY_12MO = (ONSALE_QTY_12MO - &ONSALE_QTY_12MO_LC) / (&ONSALE_QTY_12MO_UC - &ONSALE_QTY_12MO_LC);
NET_SALES_AMT_12MO_RTN = (NET_SALES_AMT_12MO_RTN - &NET_SALES_AMT_12MO_RTN_LC) / (&NET_SALES_AMT_12MO_RTN_UC - &NET_SALES_AMT_12MO_RTN_LC);
NET_SALES_AMT_12MO_SLS = (NET_SALES_AMT_12MO_SLS - &NET_SALES_AMT_12MO_SLS_LC) / (&NET_SALES_AMT_12MO_SLS_UC - &NET_SALES_AMT_12MO_SLS_LC);
AVG_UNT_RTL_CP = (AVG_UNT_RTL_CP - &AVG_UNT_RTL_CP_LC) / (&AVG_UNT_RTL_CP_UC - &AVG_UNT_RTL_CP_LC);
AVG_UNT_RTL = (AVG_UNT_RTL - &AVG_UNT_RTL_LC) / (&AVG_UNT_RTL_UC - &AVG_UNT_RTL_LC);
DISCOUNT_PCT_12MO = (DISCOUNT_PCT_12MO - &DISCOUNT_PCT_12MO_LC) / (&DISCOUNT_PCT_12MO_UC - &DISCOUNT_PCT_12MO_LC);
YEARS_ON_BOOKS = (YEARS_ON_BOOKS - &YEARS_ON_BOOKS_LC) / (&YEARS_ON_BOOKS_UC - &YEARS_ON_BOOKS_LC);
UNITS_PER_TXN_12MO_SLS = (UNITS_PER_TXN_12MO_SLS - &UNITS_PER_TXN_12MO_SLS_LC) / (&UNITS_PER_TXN_12MO_SLS_UC - &UNITS_PER_TXN_12MO_SLS_LC);
NUM_TXNS_12MO_SLS = (NUM_TXNS_12MO_SLS - &NUM_TXNS_12MO_SLS_LC) / (&NUM_TXNS_12MO_SLS_UC - &NUM_TXNS_12MO_SLS_LC);
NUM_TXNS_12MO_RTN = (NUM_TXNS_12MO_RTN - &NUM_TXNS_12MO_RTN_LC) / (&NUM_TXNS_12MO_RTN_UC - &NUM_TXNS_12MO_RTN_LC);
DIV_SHP_GP = (DIV_SHP_GP - &DIV_SHP_GP_LC) / (&DIV_SHP_GP_UC - &DIV_SHP_GP_LC);
GP_PROMOTIONS_RECEIVED_12MO = (GP_PROMOTIONS_RECEIVED_12MO - &GP_PROMOTIONS_RECEIVED_12MO_LC) / (&GP_PROMOTIONS_RECEIVED_12MO_UC - &GP_PROMOTIONS_RECEIVED_12MO_LC);
ONSALE_QTY_6MO = (ONSALE_QTY_6MO - &ONSALE_QTY_6MO_LC) / (&ONSALE_QTY_6MO_UC - &ONSALE_QTY_6MO_LC);
DAYS_LAST_PUR_GP = (DAYS_LAST_PUR_GP - &DAYS_LAST_PUR_GP_LC) / (&DAYS_LAST_PUR_GP_UC - &DAYS_LAST_PUR_GP_LC);
DAYS_LAST_PUR_CP = (DAYS_LAST_PUR_CP - &DAYS_LAST_PUR_CP_LC) / (&DAYS_LAST_PUR_CP_UC - &DAYS_LAST_PUR_CP_LC);
PLCC_TXN_PCT = (PLCC_TXN_PCT - &PLCC_TXN_PCT_LC) / (&PLCC_TXN_PCT_UC - &PLCC_TXN_PCT_LC);
NUM_PLCC_TXNS_12MO_SLS = (NUM_PLCC_TXNS_12MO_SLS - &NUM_PLCC_TXNS_12MO_SLS_LC) / (&NUM_PLCC_TXNS_12MO_SLS_UC - &NUM_PLCC_TXNS_12MO_SLS_LC);

RUN;

DATA DATALIB.GP_ALLCAMPAIGNS_RESPONDERS_3;
 SET GP_ALLCAMPAIGNS_RESPONDERS_3;
RUN;

PROC REG DATA=GP_ALLCAMPAIGNS_RESPONDERS_3 OUTEST=DATALIB.GP_ALLCAMPAIGNS_REVEST;
 MODEL NET_SALES_AMT   =      AVG_ORD_SZ_12MO ONSALE_QTY_6MO  NET_SALES_AMT_12MO_SLS
							  AVG_UNT_RTL DISCOUNT_PCT_12MO YEARS_ON_BOOKS LENGTH_PROMO 
							  GP_PROMOTIONS_RECEIVED_12MO PLCC_TXN_PCT DIV_SHP_GP
							  /VIF;
 WHERE TRAINING=1;
 OUTPUT OUT=GP_ALLCAMPAIGNS_RESPONDERS_3_P
 RSTUDENT=RSTUDENT H=LEVERAGE COOKD=COOKD DFFITS=DFFITS P=YHAT R=ERROR;
RUN;
QUIT;



PROC REG DATA=GP_ALLCAMPAIGNS_RESPONDERS_3;
 MODEL NET_SALES_AMT   =      AVG_ORD_SZ_12MO ONSALE_QTY_6MO  NET_SALES_AMT_12MO_SLS
							  AVG_UNT_RTL DISCOUNT_PCT_12MO YEARS_ON_BOOKS LENGTH_PROMO 
							  GP_PROMOTIONS_RECEIVED_12MO PLCC_TXN_PCT DIV_SHP_GP
							  /VIF NOINT;
 WHERE TRAINING=1;
 OUTPUT OUT=GP_ALLCAMPAIGNS_RESPONDERS_3_P
 RSTUDENT=RSTUDENT H=LEVERAGE COOKD=COOKD DFFITS=DFFITS P=YHAT R=ERROR;
RUN;
QUIT;

PROC UNIVARIATE DATA=GP_ALLCAMPAIGNS_RESPONDERS_3_P;
 VAR ERROR RSTUDENT;
 HISTOGRAM /NORMAL;
RUN;


PROC SORT DATA = GP_ALLCAMPAIGNS_RESPONDERS_3_P;
 BY CUSTOMER_KEY CAMPAIGN;
RUN;

PROC SQL;
 CREATE TABLE TEST AS SELECT DISTINCT CUSTOMER_KEY, COUNT(DISTINCT CAMPAIGN) AS RECORDS 
		FROM GP_ALLCAMPAIGNS_RESPONDERS_3_P GROUP BY CUSTOMER_KEY;
QUIT;

PROC FREQ DATA=TEST;
 TABLES RECORDS;
RUN;

PROC REG DATA= GP_ALLCAMPAIGNS_RESPONDERS_3_P NOPRINT;
 MODEL ERROR = ;
 BY CUSTOMER_KEY;
 OUTPUT OUT=GP_ALLCAMPAIGNS_RESPONDERS_3_P
 RSTUDENT=RSTUDENT_CUST H=LEVERAGE_CUST COOKD=COOKD_CUST P=YHAT_CUST R=ERROR_CUST;
QUIT;
