LIBNAME DATALIB "\\10.8.8.51\LV0\TANUMOY\DATASETS\MODEL REPLICATION";



PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\ON_SHOPPERS_20170910_LTV_ATT_AGG_TXT"  
OUT=DATALIB.ON_SHOPPERS_20170910_LTV_ATT_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.ON_SHOPPERS_20170910_LTV_ATT_AGG;
SET DATALIB.ON_SHOPPERS_20170910_LTV_ATT_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RENAME VAR13 = PLCC;
RENAME VAR14 = EXPECTEDLTV12;
RENAME VAR15 = ATTRITIONPROB;
;
RUN;


DATA DATALIB.ON_SHOPPERS_20170910_LTV_ATT_AGG (DROP=Z);
SET DATALIB.ON_SHOPPERS_20170910_LTV_ATT_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;


PROC MEANS DATA=DATALIB.ON_SHOPPERS_20170910_LTV_ATT_AGG N NMISS;
VAR _NUMERIC_;
RUN;

PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\ON_SHOPPERS_20170910_LAST_AGG_TXT"  
OUT=DATALIB.ON_SHOPPERS_20170910_LAST_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.ON_SHOPPERS_20170910_LAST_AGG;
SET DATALIB.ON_SHOPPERS_20170910_LAST_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RUN;

DATA DATALIB.ON_SHOPPERS_20170910_LAST_AGG (DROP=Z);
SET DATALIB.ON_SHOPPERS_20170910_LAST_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;










PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\GP_SHOPPERS_20170910_LTV_ATT_AGG_TXT"  
OUT=DATALIB.GP_SHOPPERS_20170910_LTV_ATT_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.GP_SHOPPERS_20170910_LTV_ATT_AGG;
SET DATALIB.GP_SHOPPERS_20170910_LTV_ATT_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RENAME VAR13 = PLCC;
RENAME VAR14 = EXPECTEDLTV12;
RENAME VAR15 = ATTRITIONPROB;
;
RUN;


DATA DATALIB.GP_SHOPPERS_20170910_LTV_ATT_AGG (DROP=Z);
SET DATALIB.GP_SHOPPERS_20170910_LTV_ATT_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;



PROC MEANS DATA=DATALIB.GP_SHOPPERS_20170910_LTV_ATT_AGG N NMISS;
VAR _NUMERIC_;
RUN;

PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\GP_SHOPPERS_20170910_LAST_AGG_TXT"  
OUT=DATALIB.GP_SHOPPERS_20170910_LAST_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.GP_SHOPPERS_20170910_LAST_AGG;
SET DATALIB.GP_SHOPPERS_20170910_LAST_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RUN;

DATA DATALIB.GP_SHOPPERS_20170910_LAST_AGG (DROP=Z);
SET DATALIB.GP_SHOPPERS_20170910_LAST_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;











PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\BR_SHOPPERS_20170910_LTV_ATT_AGG_TXT"  
OUT=DATALIB.BR_SHOPPERS_20170910_LTV_ATT_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.BR_SHOPPERS_20170910_LTV_ATT_AGG;
SET DATALIB.BR_SHOPPERS_20170910_LTV_ATT_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RENAME VAR13 = PLCC;
RENAME VAR14 = EXPECTEDLTV12;
RENAME VAR15 = ATTRITIONPROB;
;
RUN;


DATA DATALIB.BR_SHOPPERS_20170910_LTV_ATT_AGG (DROP=Z);
SET DATALIB.BR_SHOPPERS_20170910_LTV_ATT_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;



PROC MEANS DATA=DATALIB.BR_SHOPPERS_20170910_LTV_ATT_AGG N NMISS;
VAR _NUMERIC_;
RUN;

PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\BR_SHOPPERS_20170910_LAST_AGG_TXT"  
OUT=DATALIB.BR_SHOPPERS_20170910_LAST_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.BR_SHOPPERS_20170910_LAST_AGG;
SET DATALIB.BR_SHOPPERS_20170910_LAST_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RUN;

DATA DATALIB.BR_SHOPPERS_20170910_LAST_AGG (DROP=Z);
SET DATALIB.BR_SHOPPERS_20170910_LAST_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;









PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\AT_SHOPPERS_20170910_LTV_ATT_AGG_TXT"  
OUT=DATALIB.AT_SHOPPERS_20170910_LTV_ATT_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.AT_SHOPPERS_20170910_LTV_ATT_AGG;
SET DATALIB.AT_SHOPPERS_20170910_LTV_ATT_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RENAME VAR13 = PLCC;
RENAME VAR14 = EXPECTEDLTV12;
RENAME VAR15 = ATTRITIONPROB;
;
RUN;


DATA DATALIB.AT_SHOPPERS_20170910_LTV_ATT_AGG (DROP=Z);
SET DATALIB.AT_SHOPPERS_20170910_LTV_ATT_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;


PROC MEANS DATA=DATALIB.AT_SHOPPERS_20170910_LTV_ATT_AGG N NMISS;
VAR _NUMERIC_;
RUN;

PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\AT_SHOPPERS_20170910_LAST_AGG_TXT"  
OUT=DATALIB.AT_SHOPPERS_20170910_LAST_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.AT_SHOPPERS_20170910_LAST_AGG;
SET DATALIB.AT_SHOPPERS_20170910_LAST_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RUN;

DATA DATALIB.AT_SHOPPERS_20170910_LAST_AGG (DROP=Z);
SET DATALIB.AT_SHOPPERS_20170910_LAST_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;









PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\GO_SHOPPERS_20170910_LTV_ATT_AGG_TXT"  
OUT=DATALIB.GO_SHOPPERS_20170910_LTV_ATT_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.GO_SHOPPERS_20170910_LTV_ATT_AGG;
SET DATALIB.GO_SHOPPERS_20170910_LTV_ATT_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RENAME VAR13 = PLCC;
RUN;


DATA DATALIB.GO_SHOPPERS_20170910_LTV_ATT_AGG (DROP=Z);
SET DATALIB.GO_SHOPPERS_20170910_LTV_ATT_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;

PROC MEANS DATA=DATALIB.GO_SHOPPERS_20170910_LTV_ATT_AGG N NMISS;
VAR _NUMERIC_;
RUN;

PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\GO_SHOPPERS_20170910_LAST_AGG_TXT"  
OUT=DATALIB.GO_SHOPPERS_20170910_LAST_AGG   DBMS=DLM    REPLACE;
DELIMITER='|';
GETNAMES=NO;
RUN;

DATA DATALIB.GO_SHOPPERS_20170910_LAST_AGG;
SET DATALIB.GO_SHOPPERS_20170910_LAST_AGG;
RENAME VAR1  = CUSTOMER_KEY;
RENAME VAR2  = ITEM_QTY;
RENAME VAR3  = GROSS_SALES_AMT;
RENAME VAR4  = DISCOUNT_AMT;
RENAME VAR5  = TOT_PRD_CST_AMT;
RENAME VAR6  = NET_SALES_AMT;
RENAME VAR7  = NET_MARGIN;
RENAME VAR8  = NET_SALES_AMT_RTL;
RENAME VAR9  = NET_SALES_AMT_ONL;
RENAME VAR10 = NUM_TXNS_RTL;
RENAME VAR11 = NUM_TXNS_ONL;
RENAME VAR12 = NUM_TXNS;
RUN;

DATA DATALIB.GO_SHOPPERS_20170910_LAST_AGG (DROP=Z);
SET DATALIB.GO_SHOPPERS_20170910_LAST_AGG;
ARRAY TESTMISS(*) _NUMERIC_;                                            
DO Z = 1 TO DIM(TESTMISS);                                              
IF TESTMISS(Z)=. THEN TESTMISS(Z)=0;                                    
END;
AVG_ORD_SZ = 0;
IF NUM_TXNS NE 0 THEN AVG_ORD_SZ = NET_SALES_AMT/NUM_TXNS;
AVG_UNIT_RTL = 0;
IF ITEM_QTY NE 0 THEN AVG_UNIT_RTL = NET_SALES_AMT/ITEM_QTY; 
AVG_ORD_SZ_ONL = 0;
IF NUM_TXNS_ONL NE 0 THEN AVG_ORD_SZ_ONL = NET_SALES_AMT_ONL/NUM_TXNS_ONL;
AVG_ORD_SZ_RTL = 0;
IF NUM_TXNS_RTL NE 0 THEN AVG_ORD_SZ_RTL = NET_SALES_AMT_RTL/NUM_TXNS_RTL;
RUN;





