LIBNAME DATALIB "\\10.8.8.51\LV0\TANUMOY\DATASETS\MODEL REPLICATION";

OPTIONS MACROGEN SYMBOLGEN MLOGIC MPRINT;


DATA DATALIB.SHOPPERS18TO12MONTHS_INACTIVENOW;
INFILE "\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\SHOPPERS18TO12MONTHS_INACTIVENOW" 
DELIMITER = '|' MISSOVER DSD LRECL=32767 FIRSTOBS=1;

FORMAT CUSTOMER_KEY BEST32.;
FORMAT RETAIL_TRANSACTIONS BEST32.;
FORMAT ONLINE_TRANSACTIONS BEST32.;
FORMAT TOTAL_TRANSACTIONS BEST32.;
FORMAT ITEM_QTY BEST32.;
FORMAT GROSS_SALES_AMT BEST32.;
FORMAT DISCOUNT_AMT BEST32.;
FORMAT NET_SALES_AMT BEST32.;
FORMAT TOT_PRD_CST_AMT BEST32.;
FORMAT CARD_STATUS BEST32.;


INFORMAT CUSTOMER_KEY BEST32.;
INFORMAT RETAIL_TRANSACTIONS BEST32.;
INFORMAT ONLINE_TRANSACTIONS BEST32.;
INFORMAT TOTAL_TRANSACTIONS BEST32.;
INFORMAT ITEM_QTY BEST32.;
INFORMAT GROSS_SALES_AMT BEST32.;
INFORMAT DISCOUNT_AMT BEST32.;
INFORMAT NET_SALES_AMT BEST32.;
INFORMAT TOT_PRD_CST_AMT BEST32.;
INFORMAT CARD_STATUS BEST32.;

INPUT
CUSTOMER_KEY
RETAIL_TRANSACTIONS
ONLINE_TRANSACTIONS
TOTAL_TRANSACTIONS
ITEM_QTY
GROSS_SALES_AMT
DISCOUNT_AMT
NET_SALES_AMT
TOT_PRD_CST_AMT
CARD_STATUS
;
RUN;

PROC IMPORT DATAFILE="\\10.8.8.51\LV0\TANUMOY\DATASETS\FROM HIVE\MARKETABLENOW.TXT"  OUT=DATALIB.MARKETABLENOW   DBMS=DLM    REPLACE;
DELIMITER=',';
GETNAMES=YES;
RUN;


PROC SQL;
CREATE TABLE MARKETABLEINACTIVES AS SELECT 
T1.*, T2.*
FROM
DATALIB.SHOPPERS18TO12MONTHS_INACTIVENOW T1
INNER JOIN
DATALIB.MARKETABLENOW T2
ON
T1.CUSTOMER_KEY=T2.CUST_KEY;
QUIT;



PROC FREQ DATA = MARKETABLEINACTIVES;
TABLE CELL_LABEL;
RUN;

PROC MEANS DATA = MARKETABLEINACTIVES;
VAR NET_SALES_AMT;
CLASS CELL_LABEL;
RUN;

PROC UNIVARIATE DATA = MARKETABLEINACTIVES;
VAR NET_SALES_AMT;
CLASS CELL_LABEL;
RUN;

PROC SQL;
SELECT COUNT(*) FROM MARKETABLEINACTIVES WHERE NET_SALES_AMT > 67 and CELL_LABEL = 'inactive noncard';
SELECT COUNT(*) FROM MARKETABLEINACTIVES WHERE NET_SALES_AMT > 0 and CELL_LABEL = 'inactive card';
QUIT;

DATA NONCARD;
SET MARKETABLEINACTIVES;
WHERE NET_SALES_AMT > 67 and CELL_LABEL = 'inactive noncard';
KEEP CUST_KEY;
RUN;


DATA CARD;
SET MARKETABLEINACTIVES;
WHERE NET_SALES_AMT > 0 and CELL_LABEL = 'inactive card';
KEEP CUST_KEY;
RUN;



PROC EXPORT DATA=NONCARD
			OUTFILE="Z:\TANUMOY\DATASETS\MODEL REPLICATION\NONCARD.TXT"
            DBMS=DLM REPLACE;
     DELIMITER=",";
RUN;


PROC EXPORT DATA=CARD
			OUTFILE="Z:\TANUMOY\DATASETS\MODEL REPLICATION\CARD.TXT"
            DBMS=DLM REPLACE;
     DELIMITER=",";
RUN;
